// Spanish catalog. Slugs, prices and images mirror catalog.ts exactly —
// only human-readable text is localized. First-pass translation; have a
// native speaker review before heavy ad spend.

import type { Category, City, Experience, Tour } from "@/lib/catalog";

export const CANCELLATION_ES =
  "Cancelación gratuita hasta 7 días antes de la experiencia. Reembolso completo si el anfitrión cancela la sesión.";

export const citiesEs: City[] = [
  {
    slug: "tokyo", title: "Tokio", jp: "東京", img: "/images/city-tokyo.jpg",
    lead: "Tokio guarda sus tradiciones tras puertas discretas, a pocas calles del neón. Nuestras clases magistrales te sientan junto a quienes las mantienen vivas — un chef de sushi en su propia barra, luchadores en el entrenamiento matinal, un forjador de katanas en su fragua — siempre con un guía intérprete privado a tu lado.",
  },
  {
    slug: "kyoto", title: "Kioto", jp: "京都", img: "/images/city-kyoto.jpg",
    lead: "Kioto es donde los rituales de Japón todavía se viven a diario. Nuestras experiencias abren puertas que permanecen cerradas para la mayoría — una velada con una geiko, un cuenco de té batido por una maestra, un paseo en seda por Higashiyama — cada una con un guía intérprete privado que traduce cada palabra.",
  },
];

export const categoriesEs: Category[] = [
  { slug: "sushi", title: "Sushi", tag: "Gastronomía", mark: "寿", img: "/images/cat-sushi.jpg",
    lead: "En Japón, el sushi es un oficio que se mide en décadas, no en recetas. Estas clases magistrales en grupos reducidos te ponen detrás de la barra con chefs en activo de Tokio y Kioto — moldeando, sazonando y probando como ellos, con un guía intérprete a tu lado." },
  { slug: "sumo", title: "Sumo", tag: "Tradicional", mark: "相", img: "/images/cat-sumo.jpg",
    lead: "El sumo es el deporte vivo más antiguo de Japón, y su día a día es mucho más íntimo que el estadio. Observa de cerca el entrenamiento matinal en una cuadra en activo y entiende la disciplina detrás de la ceremonia, con tu guía explicando cada ritual en voz baja." },
  { slug: "tea-ceremony", title: "Ceremonia del té", tag: "Tradicional", mark: "茶", img: "/images/cat-tea.jpg",
    lead: "La ceremonia del té destila la hospitalidad japonesa en un solo cuenco. Siéntate con una maestra de té en activo, aprende los gestos y comparte una hora serena donde cada movimiento tiene sentido — traducido con delicadeza, sin interrupciones." },
  { slug: "kimono", title: "Kimono", tag: "Tradicional", mark: "着", img: "/images/cat-kimono.jpg",
    lead: "Un kimono es arquitectura vestida: seda, estación y postura en armonía. Déjate vestir como es debido por estilistas profesionales en Tokio o Kioto, y pasea por jardines y callejones de farolillos hechos para verse desde dentro de uno." },
  { slug: "geisha", title: "Geisha", tag: "Tradicional", mark: "芸", img: "/images/cat-geisha.jpg",
    lead: "Una velada con una geiko es la invitación más celosamente guardada de Kioto. Comparte conversación, danza y cocina de temporada en un entorno privado, con un intérprete que deja fluir el intercambio en tu idioma." },
  { slug: "swordsmith", title: "Forja de katanas", tag: "Tradicional", mark: "刀", img: "/images/cat-sword.jpg",
    lead: "La espada japonesa son mil años de metalurgia en una sola curva. Visita una fragua en activo, observa a un forjador titulado plegar el acero al modo tradicional y sostén la historia en tus manos — con guía y traducción en todo momento." },
  { slug: "anime-nail-art", title: "Nail art de anime", tag: "Cultura pop", mark: "爪", img: "/images/cat-nail.jpg",
    lead: "Las artistas de uñas de Tokio tratan cada uña como un lienzo. Trae a tu personaje favorito y llévate arte fan portátil pintado por una artista que vive de esto — el lado más ligero y juguetón del oficio japonés." },
];

export const experiencesEs: Experience[] = [
  {
    slug: "sushi-masterclass", city: "tokyo", category: "sushi",
    title: "Clase magistral de sushi Edo-mae",
    tagline: "Moldea nigiri con un chef de tercera generación en su propia barra",
    duration: "2,5 horas", price: "¥45.000", group: "Privado · máx. 6", ages: "A partir de 8 años", area: "Tokio (zona de Tsukiji)",
    img: "/images/exp-sushi.jpg", alt: "Barra de sushi omakase de madera de hinoki",
    gallery: [{ img: "/images/cat-sushi.jpg", alt: "Chef de sushi cortando pescado sobre una tabla de madera" }],
    whatYoullDo: [
      "Siéntate en la barra del propio chef, cerrada al público durante tu sesión.",
      "Aprende a moldear el shari, sazonar el neta y prensar nigiri con su corrección directa.",
      "Prueba cada pieza recién hecha, tal y como debe comerse el sushi Edo-mae.",
      "Termina con la selección del chef, servida para ti como su invitado.",
    ],
    master: { quote: "Mi abuelo sostenía mis manos sobre el arroz. Hoy, yo sostengo las tuyas.", title: "Un chef de sushi Edo-mae de tercera generación", bio: "Se formó con su padre y su abuelo en la misma barra donde tú estarás, en un barrio marcado por el antiguo mercado de Tsukiji. Rara vez acepta alumnos; esta sesión es la excepción. El nombre de su local se comparte al confirmar la reserva." },
    itinerary: ["10:00 — Encuentro con tu guía intérprete cerca del local", "10:15 — Presentaciones, delantal, corte y shari", "11:15 — Moldeado de nigiri en la barra", "12:00 — Degustación y plato final del chef", "12:30 — Fin de la experiencia"],
    goodToKnow: ["Se celebra por la mañana, antes de abrir el local; los días exactos dependen de la agenda del chef.", "El pescado crudo es el centro de la sesión — cuéntanos tus alergias y lo adaptamos.", "Es práctica y de pie la mayor parte del tiempo; se facilitan delantales.", "Puedes hacer fotos; pedimos que la fachada y los rótulos queden fuera del encuadre."],
    story: { heading: "La historia del sushi Edo-mae", body: "Edo-mae — «frente a Edo» — designaba el pescado de la bahía de Tokio, curado, prensado o marcado para aguantar un día sin hielo. Las técnicas sobrevivieron a la refrigeración porque saben mejor, no por ser antiguas. Lo que aprenderás en esta barra es ese repertorio: vinagre, sal, kombu y tiempo, pieza a pieza." },
  },
  {
    slug: "sumo-morning-practice", city: "tokyo", category: "sumo",
    title: "Dentro del entrenamiento matinal de sumo",
    tagline: "A pie de ring en una cuadra en activo mientras arranca el día",
    duration: "2 horas", price: "¥38.000", group: "Grupo reducido · máx. 8", ages: "A partir de 10 años", area: "Tokio (zona de Ryogoku)",
    img: "/images/exp-sumo.jpg", alt: "Luchadores de sumo entrenando en el ring de una cuadra de Tokio",
    gallery: [{ img: "/images/cat-sumo.jpg", alt: "Luchadores de sumo en la ceremonia de entrada al ring" }],
    whatYoullDo: [
      "Entra con tu guía en una cuadra de sumo en activo antes de que despierte la ciudad.",
      "Observa el keiko — el entrenamiento matinal — desde tatamis a pocos metros del ring.",
      "Entiende cada ejercicio y ritual sobre la marcha, en tu idioma.",
      "Saluda brevemente a los luchadores tras la práctica, si su agenda lo permite.",
    ],
    master: { quote: "El entrenamiento no es un espectáculo. Pero esta mañana, la puerta está abierta para ti.", title: "Una cuadra de sumo del barrio de Ryogoku", bio: "La cuadra lleva décadas formando luchadores clasificados en el barrio histórico del sumo de Tokio. Las visitas son limitadas para no perturbar la práctica; tu guía te explicará la etiqueta antes de entrar. El nombre de la cuadra se comparte al confirmar la reserva." },
    itinerary: ["07:30 — Encuentro con tu guía intérprete en Ryogoku", "07:45 — Normas de etiqueta y entrada a la cuadra", "08:00 — Entrenamiento matinal desde los tatamis", "09:15 — Breve saludo con los luchadores (según agenda)", "09:30 — Fin de la experiencia"],
    goodToKnow: ["La práctica sigue el calendario de torneos; algunas semanas no hay disponibilidad.", "Se exige silencio durante el entrenamiento; tu guía traduce en susurros.", "Estarás sentado en tatami hasta 90 minutos; hay cojines disponibles.", "Viste con discreción; no se permite flash dentro de la cuadra."],
    story: { heading: "El mundo dentro de una cuadra de sumo", body: "El sumo profesional se vive, no solo se representa. Los luchadores comparten techo, cocina y una jerarquía estricta, y el ring matinal es donde todo se hace visible: los novatos barren el dohyo, los veteranos pelean los últimos y más duros combates. Ver el keiko es ver toda la sociedad de este deporte de una vez." },
  },
  {
    slug: "kimono-photo-walk", city: "tokyo", category: "kimono",
    title: "Vestido de kimono y paseo por el jardín",
    tagline: "Vestido por una estilista profesional y paseo por un jardín clásico",
    duration: "3 horas", price: "¥40.000", group: "Privado · máx. 4", ages: "Todas las edades", area: "Tokio (barrio de jardines tradicionales)",
    img: "/images/exp-kimono.jpg", alt: "Mujer en kimono rojo junto a un estanque de carpas en un jardín japonés",
    gallery: [{ img: "/images/cat-kimono.jpg", alt: "Kimono antiguo de seda con motivo de faisanes y peonías" }],
    whatYoullDo: [
      "Elige entre un vestuario seleccionado de kimonos de seda acordes a la estación.",
      "Déjate vestir como es debido — cada capa, pliegue y nudo — por una estilista profesional.",
      "Pasea por un jardín clásico mientras tu guía te cuenta su diseño y su historia.",
      "Disfruta de tiempo sin prisas para fotos en los mejores rincones del jardín.",
    ],
    master: { quote: "Un kimono no se pone: se construye. Y yo lo construiré sobre ti.", title: "Una estilista profesional de kimono", bio: "Lleva más de veinte años vistiendo a clientes para bodas, ceremonias y rodajes, y elige cada conjunto según la persona y la estación, no de un perchero de disfraces. La ubicación de su estudio se comparte al confirmar la reserva." },
    itinerary: ["10:00 — Encuentro con tu guía intérprete en el estudio", "10:15 — Selección del kimono y vestido", "11:15 — Paseo por el jardín y fotografías", "12:45 — Regreso, cambio de ropa y té", "13:00 — Fin de la experiencia"],
    goodToKnow: ["Hay kimonos en una amplia gama de tallas; dinos tu altura con antelación.", "Caminar cómodo es parte de la experiencia; se facilitan calcetines tabi.", "Si llueve, el paseo sigue por los caminos cubiertos y la casa de té del jardín.", "Se puede añadir un fotógrafo profesional bajo petición."],
    story: { heading: "Por qué importa el vestido", body: "Un kimono no se pone; se construye — capa sobre capa, ajustado al cuerpo hasta que la silueta es la correcta. Bien vestido cambia tu forma de estar y de caminar, y por eso el jardín viene después del vestidor: fue diseñado para quien pasea al ritmo de un kimono." },
  },
  {
    slug: "katana-forge-visit", city: "tokyo", category: "swordsmith",
    title: "Katana: visita la fragua de un forjador",
    tagline: "Observa a un forjador titulado plegar el acero al modo tradicional",
    duration: "3 horas", price: "¥90.000", group: "Privado · máx. 4", ages: "A partir de 12 años", area: "Gran Tokio (zona de talleres)",
    img: "/images/cat-sword.jpg", alt: "Hoja de katana pulida fotografiada sobre negro",
    gallery: [],
    whatYoullDo: [
      "Viaja con tu guía hasta una fragua en activo que rara vez abre sus puertas.",
      "Observa el acero tamahagane calentarse, martillearse y plegarse en el yunque.",
      "Sostén hojas terminadas y descubre cómo el pulidor revela el hamon.",
      "Pregunta lo que quieras al forjador — tu guía traduce toda la conversación.",
    ],
    master: { quote: "El acero recuerda cada golpe. Ven a verlo recordar.", title: "Un forjador de espadas japonés titulado", bio: "Es uno de los pocos herreros autorizados hoy para forjar nihonto, y trabaja en la fragua tradicional de carbón con un único aprendiz. Los días de forja son irregulares, así que las fechas se confirman una a una. La ubicación de la fragua se comparte al confirmar la reserva." },
    itinerary: ["09:30 — Encuentro con tu guía intérprete; viaje juntos a la fragua", "10:30 — Introducción a la fragua y sus herramientas", "11:00 — Demostración de forja en el yunque", "12:00 — Manejo de hojas y preguntas con el forjador", "12:30 — Fin de la experiencia (regreso con tu guía)"],
    goodToKnow: ["La fragua es calurosa y ruidosa durante las demostraciones; se facilita protección auditiva.", "Cerca del fuego se requiere calzado cerrado y ropa de fibras naturales.", "Las fechas dependen del calendario de producción del forjador — reserva pronto.", "Las hojas se manejan solo bajo la supervisión directa del maestro."],
    story: { heading: "Mil años en una sola curva", body: "La espada japonesa sobrevive porque su elaboración nunca se simplificó. El acero se sigue fundiendo a partir de arena de hierro, se pliega para expulsar impurezas y se templa en agua creando la curva y el hamon en un único instante de riesgo. Cada forjador titulado en activo es una línea directa con ese método intacto." },
  },
  {
    slug: "anime-nail-art-session", city: "tokyo", category: "anime-nail-art",
    title: "Sesión de nail art de anime",
    tagline: "Tu personaje favorito, pintado por una artista de uñas de Tokio",
    duration: "2 horas", price: "¥18.000", group: "Privado · máx. 2", ages: "Todas las edades", area: "Tokio (zona de Akihabara / Harajuku)",
    img: "/images/cat-nail.jpg", alt: "Calle de Akihabara iluminada de neón por la noche",
    gallery: [],
    whatYoullDo: [
      "Comparte con antelación tus personajes o ilustraciones favoritas con la artista.",
      "Observa cómo nacen ilustraciones diminutas pintadas a mano, uña a uña.",
      "Charla con la artista sobre la cultura del nail art y el fan art de Tokio mientras trabaja.",
      "Llévate un arte en gel duradero — y sus consejos de cuidado.",
    ],
    master: { quote: "Tráeme a tu personaje favorito. Lo pintaré en ocho milímetros.", title: "Una artista de uñas especializada en personajes de Tokio", bio: "Su agenda la llenan fans que vuelan hasta aquí por su trabajo pintado a mano, desde franquicias clásicas hasta los estrenos de esta temporada. Pinta a pulso con pinceles más finos que la mina de un lápiz. La ubicación de su salón se comparte al confirmar la reserva." },
    itinerary: ["14:00 — Encuentro con tu guía intérprete en el salón", "14:10 — Consulta de diseño sobre tus referencias", "14:30 — Sesión de pintura", "15:50 — Capa final y cuidados", "16:00 — Fin de la experiencia"],
    goodToKnow: ["Envía imágenes de referencia al reservar para que la artista prepare los colores.", "El arte en gel suele durar de tres a cuatro semanas con uso normal.", "Los diseños complejos pueden alargar la sesión; el horario se confirma antes.", "Esta experiencia tiene un precio más ligero que nuestras clases magistrales — no por ello menos artesanal."],
    story: { heading: "Fan art que puedes llevar puesto", body: "El nail art creció junto a la cultura de personajes de Japón, y en Tokio ambos se fundieron en un género propio: microilustración pintada sobre un lienzo móvil más pequeño que un sello. Las mejores artistas tienen lista de espera de semanas entre el público local. Esta sesión te abre una de esas sillas." },
  },
  {
    slug: "evening-with-geiko", city: "kyoto", category: "geisha",
    title: "Banquete ozashiki con maiko y geiko",
    tagline: "Un salón privado en Kioto: cena, danza y juegos de sobremesa con geiko y maiko",
    duration: "2 horas", price: "¥139.600", priceUnit: "group", group: "Privado · 2–40 personas", ages: "Todas las edades", area: "Kioto (zona de Gion / Higashiyama)",
    img: "/images/exp-geisha.jpg", alt: "Maiko interpretando una danza tradicional con abanico",
    gallery: [{ img: "/images/cat-geisha.jpg", alt: "Maiko con atuendo completo en un barrio de casas de té de Kioto" }],
    cancellation: "Una vez confirmada la reserva se aplican gastos de cancelación: 50% hasta 4 días antes, 75% entre 3 y 2 días antes, 100% desde la víspera (hora de Japón; no presentarse, 100%). Los cambios de fecha siguen la misma escala y reducir el grupo aplica la tarifa a las plazas liberadas. Si no se puede asegurar una geiko o maiko para tu fecha, se reembolsa el importe completo.",
    whatYoullDo: [
      "Acomódate en tu propio salón de banquete privado — nunca compartido con otros clientes.",
      "Cena cocina de temporada de Kioto mientras geiko y maiko se unen a tu mesa para conversar.",
      "Contempla una danza a un brazo de distancia y prueba los juegos de sobremesa ozashiki.",
      "Termina con fotos conmemorativas junto a tus anfitrionas.",
    ],
    master: { quote: "Por una noche, esta sala es tuya. Ven, hablemos.", title: "Geiko y maiko del hanamachi de Kioto", bio: "Tu velada la acogen geiko o maiko en activo del mundo de la flor y el sauce de Kioto, contratadas especialmente para tu fecha. El local es una casa de banquetes privada del barrio de Gion / Higashiyama; su nombre y dirección se comparten al confirmar la reserva." },
    itinerary: ["10 min antes — Llegada al local con tu guía (dirección en la confirmación)", "0:00 — Bienvenida a tu salón privado; comienza el banquete", "0:30 — Geiko y maiko se unen a tu mesa; conversación durante la cena", "1:15 — Danza y juegos de sobremesa ozashiki", "1:50 — Fotos conmemorativas", "2:00 — Fin de la velada"],
    goodToKnow: [
      "Se celebra todos los días salvo las fiestas de Año Nuevo, con inicios entre las 12:00 y las 20:30 — reserva con al menos 3 días de antelación (cierre a las 17:00, hora de Japón).",
      "El precio es por grupo, todo incluido: ¥139.600 para 2 personas, ¥157.500 para 3, ¥166.000 para 4, ¥190.000 para 5; grupos mayores (hasta 40) bajo consulta.",
      "En temporada alta (15 mar – 31 may y 1 oct – 30 nov) rigen tarifas superiores (desde ¥159.600 para 2 personas).",
      "Niños: menores de 2 años gratis sin comida, de 3 a 11 años mitad de la tarifa de adulto, desde 12 años tarifa de adulto con el menú completo.",
      "Atendemos alergias y restricciones alimentarias — indícalo al reservar.",
      "¿Quieres una sala más animada? Se puede añadir una geiko o maiko adicional por ¥60.500.",
    ],
    story: { heading: "El mundo del karyukai", body: "El «mundo de la flor y el sauce» de Kioto funciona desde hace tres siglos a base de presentación y confianza. Una geiko no es una artista de alquiler, sino una maestra cuyas veladas se conceden a través de relaciones entre casas de té y mecenas. Sentarte en esa sala, con la conversación fluyendo en tu idioma, es el acceso más raro que ofrece Kioto." },
  },
  {
    slug: "tea-ceremony-with-master", city: "kyoto", category: "tea-ceremony",
    title: "Ceremonia del té con una maestra",
    tagline: "Una hora serena de temae en una sala de té de Kioto, cuenco a cuenco",
    duration: "1,5 horas", price: "¥30.000", group: "Privado · máx. 6", ages: "Todas las edades", area: "Kioto (barrio de templos)",
    img: "/images/craft-hands.jpg", alt: "Anfitriona de la ceremonia del té dejando un cuenco sobre el tatami",
    gallery: [{ img: "/images/cat-tea.jpg", alt: "Anfitriona preparando matcha en una reunión de té al aire libre" }],
    whatYoullDo: [
      "Entra a una sala de té en activo por el sendero de su jardín, como los invitados desde hace siglos.",
      "Contempla un temae completo — la coreografía del carbón, el agua, el batidor y el cuenco.",
      "Bate tu propio cuenco de matcha con la guía de la maestra.",
      "Descubre cómo se eligen utensilios, caligrafía y flores para este día y esta estación.",
    ],
    master: { quote: "Una vez, un encuentro. Este cuenco de té no volverá a existir.", title: "Una maestra de té de Kioto en activo", bio: "Titulada en una de las grandes escuelas del té, practica desde hace más de tres décadas y celebra reuniones durante todo el año. Su sala de té está cerca de uno de los barrios de templos de Kioto; la ubicación exacta se comparte al confirmar la reserva." },
    itinerary: ["10:00 — Encuentro con tu guía intérprete cerca de la sala de té", "10:10 — Sendero del jardín, purificación y entrada", "10:20 — Temae de la maestra, primeros cuencos y dulces", "10:50 — Bate tu propio cuenco; utensilios y conversación", "11:30 — Fin de la experiencia"],
    goodToKnow: ["Se sienta en tatami; puedes estirar las piernas y hay taburetes bajos.", "Se agradecen los calcetines blancos; te lo recordaremos la víspera.", "Los dulces no contienen productos animales; otras necesidades, con aviso.", "El movimiento y las fotos se pausan durante el temae — tu guía te indicará."],
    story: { heading: "Una vez, un encuentro", body: "Ichigo ichie — la idea de que esta reunión, con estas personas, ocurre exactamente una vez — es el corazón de la ceremonia del té. Todo en la sala responde al día: la caligrafía, la flor, el esmalte del cuenco frente a la estación. El ritual no es espectáculo sino atención, ofrecida a los invitados cuenco a cuenco." },
  },
  {
    slug: "kimono-higashiyama-walk", city: "kyoto", category: "kimono",
    title: "Kimono y paseo de farolillos por Higashiyama",
    tagline: "Vestida de seda por las calles más legendarias de Kioto a la hora dorada",
    duration: "3 horas", price: "¥40.000", group: "Privado · máx. 4", ages: "Todas las edades", area: "Kioto (zona de Higashiyama)",
    img: "/images/cat-kimono.jpg", alt: "Kimono antiguo de seda con motivo de faisanes y peonías",
    gallery: [{ img: "/images/city-kyoto.jpg", alt: "Calle Yasaka-dori con farolillos y la pagoda de Yasaka al amanecer" }],
    whatYoullDo: [
      "Déjate vestir en seda acorde a la estación por una profesional del kitsuke de Kioto.",
      "Recorre las calles empedradas de Higashiyama mientras se encienden los farolillos.",
      "Escucha la historia de las calles de la pagoda de boca de tu guía mientras caminas.",
      "Haz una pausa para fotos donde la multitud se disipa y la luz es mejor.",
    ],
    master: { quote: "Camina estas calles en seda a la hora de los farolillos y entenderás por qué seguimos vistiendo así.", title: "Una profesional del kitsuke (vestido de kimono) de Kioto", bio: "Formada en el vestido formal para las temporadas de ceremonias de Kioto, elige de un vestuario de seda vintage y contemporánea, no de poliéster de alquiler. Su estudio en Higashiyama está a un paso de la ruta; la dirección se comparte al confirmar la reserva." },
    itinerary: ["15:30 — Encuentro con tu guía intérprete en el estudio", "15:45 — Selección y vestido", "16:45 — Paseo por Higashiyama: calles de piedra, pagoda y farolillos", "18:15 — Regreso y cambio de ropa", "18:30 — Fin de la experiencia"],
    goodToKnow: ["La ruta es empedrada y con suave pendiente; se te ajustan zori resistentes.", "Las plazas de hora dorada son limitadas — reserva pronto en otoño y primavera.", "Si llueve, el paseo continúa con paraguas tradicionales (salen preciosos en fotos).", "Se puede añadir un fotógrafo profesional bajo petición."],
    story: { heading: "Calles hechas para la seda", body: "Los callejones de Higashiyama los moldearon peregrinos, casas de té y talleres durante cinco siglos, y su escala sigue hecha para una persona a pie en kimono. Recorrerlos en seda a la hora de los farolillos no es disfrazarse: es ver las calles como fueron diseñadas para verse." },
  },
  {
    slug: "kyoto-sushi-class", city: "kyoto", category: "sushi",
    title: "Clase de sushi de Kioto y obanzai",
    tagline: "Saba-zushi prensado y cocina casera de Kioto con un chef veterano",
    duration: "2,5 horas", price: "¥35.000", group: "Privado · máx. 6", ages: "A partir de 8 años", area: "Kioto (centro de la ciudad)",
    img: "/images/cat-sushi.jpg", alt: "Chef cortando pescado sobre una tabla de madera",
    gallery: [],
    whatYoullDo: [
      "Descubre por qué Kioto, sin mar, construyó su propia tradición de sushi con pescado curado.",
      "Prensa tu propio saba-zushi — sushi de caballa — en un molde de madera.",
      "Cocina dos o tres obanzai, los platos caseros de Kioto, junto al chef.",
      "Sentaos juntos a comer lo que habéis preparado, con té de temporada.",
    ],
    master: { quote: "Kioto no tenía mar, así que inventamos nuestro propio sushi. Te enseñaré el truco.", title: "Un chef veterano de Kioto", bio: "Lleva más de treinta años cocinando profesionalmente la cocina casera de Kioto y enseña las técnicas de sushi prensado que la ciudad desarrolló lejos del mar. La ubicación de su cocina se comparte al confirmar la reserva." },
    itinerary: ["10:30 — Encuentro con tu guía intérprete en la cocina", "10:45 — Introducción: el sushi de Kioto, curado y no crudo", "11:00 — Prensado del saba-zushi; cocina de obanzai", "12:15 — Almuerzo juntos en la barra", "13:00 — Fin de la experiencia"],
    goodToKnow: ["La caballa curada es la protagonista; hay alternativas para alergias.", "Totalmente práctica; delantales y todo el equipo incluidos.", "Recetas en inglés para llevar a casa.", "Los ingredientes de mercado hacen que los obanzai cambien con la estación."],
    story: { heading: "Sushi, lejos del mar", body: "Antes del ferrocarril, el pescado fresco de mar no llegaba a Kioto — así que la ciudad perfeccionó la conservación. La caballa salada en la costa viajaba por el «saba kaido», la ruta de la caballa, y se prensaba sobre arroz como saba-zushi. El sushi de Kioto es el sabor de esa geografía, y aún se hace en casa hoy." },
  },
];

export const toursEs: Tour[] = [
  {
    slug: "tokyo-private-day-tour", city: "tokyo",
    title: "Tour privado de un día por Tokio",
    tagline: "Ocho horas con un guía titulado, a la medida de tus intereses",
    duration: "8 horas", price: "¥60.000", group: "Grupo privado",
    img: "/images/city-tokyo.jpg", alt: "Puerta Kaminarimon del templo Senso-ji de noche",
    description: "Un día completo en Tokio con un guía privado titulado, planificado alrededor de lo que te importa — gastronomía, artesanía, arquitectura, cultura pop — y capaz de integrar cualquiera de nuestras clases magistrales de Tokio en la ruta. Transporte, horarios y reservas quedan resueltos; tú solo sal del hotel.",
  },
  {
    slug: "kyoto-private-day-tour", city: "kyoto",
    title: "Tour privado de un día por Kioto",
    tagline: "Templos, té y callejones con un guía que conoce las horas tranquilas",
    duration: "8 horas", price: "¥60.000", group: "Grupo privado",
    img: "/images/tour-journey.jpg", alt: "Torii bermellón en un sendero del santuario Fushimi Inari",
    description: "Un día completo en Kioto con un guía privado titulado que planifica esquivando las multitudes — puertas tempranas, jardines tranquilos, la calle correcta a la hora correcta. Combínalo con nuestra ceremonia del té, el kimono o la velada con geiko para construir un día que se sienta una sola historia y no una lista.",
  },
];
