// French catalog. Slugs, prices and images mirror catalog.ts exactly —
// only human-readable text is localized. Vouvoiement throughout.

import type { Category, City, Experience, Tour } from "@/lib/catalog";

export const CANCELLATION_FR =
  "Annulation gratuite jusqu'à 7 jours avant l'expérience. Remboursement intégral si la séance est annulée par le lieu.";

export const citiesFr: City[] = [
  {
    slug: "tokyo", title: "Tokyo", jp: "東京", img: "/images/city-tokyo.jpg",
    lead: "Tokyo garde ses traditions derrière des portes discrètes, à quelques rues des néons. Nos masterclasses vous assoient auprès de ceux qui les font vivre — un chef sushi à son propre comptoir, des lutteurs à l'entraînement du matin, un forgeron de katana à sa forge — toujours avec un guide-interprète privé à vos côtés.",
  },
  {
    slug: "kyoto", title: "Kyoto", jp: "京都", img: "/images/city-kyoto.jpg",
    lead: "Découvrez un autre visage de Kyoto à travers ses traditions vivantes. Passez une soirée privée avec une geiko ou une maiko — dîner, danse et conversation dans votre propre salon — en attendant d'autres expériences à Kyoto autour de la cuisine, de l'artisanat et des accès privilégiés.",
  },
];

export const categoriesFr: Category[] = [
  { slug: "sushi", title: "Sushi", tag: "Gastronomie", mark: "寿", img: "/images/cat-sushi.jpg",
    lead: "Au Japon, le sushi est un métier qui se mesure en décennies, pas en recettes. Ces masterclasses en tout petit groupe vous placent derrière le comptoir avec des chefs en activité à Tokyo et Kyoto — façonner, assaisonner et goûter comme eux, avec un guide-interprète à vos côtés." },
  { slug: "sumo", title: "Sumo", tag: "Traditionnel", mark: "相", img: "/images/cat-sumo.jpg",
    lead: "Le sumo est le plus ancien sport vivant du Japon, et son quotidien est bien plus intime que le stade. Observez de près l'entraînement matinal d'une écurie en activité et comprenez la discipline derrière le cérémonial, votre guide expliquant chaque rituel à voix basse." },
  { slug: "tea-ceremony", title: "Cérémonie du thé", tag: "Traditionnel", mark: "茶", img: "/images/cat-tea.jpg",
    lead: "La cérémonie du thé condense l'hospitalité japonaise en un seul bol. Asseyez-vous face à une maîtresse de thé en activité, apprenez les gestes et partagez une heure sereine où chaque mouvement a un sens — traduit avec délicatesse, sans interruption." },
  { slug: "kimono", title: "Kimono", tag: "Traditionnel", mark: "着", img: "/images/cat-kimono.jpg",
    lead: "Un kimono est une architecture que l'on porte : soie, saison et maintien en harmonie. Laissez-vous habiller dans les règles par des stylistes professionnelles à Tokyo ou Kyoto, puis parcourez jardins et ruelles aux lanternes faites pour être vues de l'intérieur d'un kimono." },
  { slug: "geisha", title: "Geisha", tag: "Traditionnel", mark: "芸", img: "/images/geiko-dance.jpg",
    lead: "Une soirée avec une geiko est l'invitation la plus gardée de Kyoto. Conversation, danse et cuisine de saison dans un cadre privé, avec un interprète qui laisse l'échange couler naturellement dans votre langue." },
  { slug: "swordsmith", title: "Forgeron de sabres", tag: "Traditionnel", mark: "刀", img: "/images/cat-sword.jpg",
    lead: "Le sabre japonais, c'est mille ans de métallurgie dans une seule courbe. Visitez une forge en activité, regardez un forgeron agréé plier l'acier selon la tradition, et tenez l'histoire entre vos mains — guidé et traduit d'un bout à l'autre." },
  { slug: "anime-nail-art", title: "Nail art anime", tag: "Pop culture", mark: "爪", img: "/images/cat-nail.jpg",
    lead: "Les nail artists de Tokyo traitent l'ongle comme une toile. Apportez votre personnage ou motif préféré et repartez avec un fan art à porter, réalisé par une artiste qui fait cela tous les jours — la face légère et joueuse de l'artisanat japonais." },
  { slug: "calligraphy", title: "Calligraphie", tag: "Arts et artisanat", mark: "書", img: "/images/kanji-works-table.jpg",
    lead: "Un pinceau, de l'encre noire et un seul caractère. Apprenez les traits avec une professeure, choisissez des kanji qui portent le sens de votre prénom et repartez avec une œuvre faite de vos mains." },
];

export const experiencesFr: Experience[] = [
  {
    slug: "kanji-name-calligraphy", city: "tokyo", category: "calligraphy",
    title: "Votre prénom en kanji : cours de calligraphie au pinceau à Tokyo",
    tagline: "Deux heures avec une professeure de calligraphie à Tokyo. Dites-lui ce que signifie votre prénom, choisissez le kanji qui le porte, apprenez les traits et tracez votre propre œuvre sur un shikishi, scellée d'un cachet rouge et à emporter sur son support en bois.",
    duration: "Environ 2 h", price: "¥16,800", group: "Privé · 1 à 4 personnes", ages: "Dès 10 ans", area: "Tokyo (Shinjuku)",
    img: "/images/kanji-hero-results.jpg", alt: "Deux participants souriants avec les kanji qu'ils ont tracés lors d'un cours de calligraphie à Tokyo",
    gallery: [
      { img: "/images/kanji-teacher-demo.jpg", alt: "La professeure montre un trait pendant qu'un participant s'exerce à côté" },
      { img: "/images/kanji-guests-works.jpg", alt: "Deux participants avec leurs kanji terminés : 灯 (lumière) et 夢 (rêve)" },
      { img: "/images/kanji-works-table.jpg", alt: "Œuvres terminées qui sèchent, chacune avec son cachet rouge" },
      { img: "/images/kanji-brush-focus.jpg", alt: "Un participant concentré sur son œuvre finale" },
      { img: "/images/kanji-teacher-yume.jpg", alt: "La professeure tenant 夢 (rêve) dans un style ludique" },
      { img: "/images/kanji-writing-together.jpg", alt: "Deux participants s'exercent à la table commune" },
      { img: "/images/kanji-teacher-guides.jpg", alt: "La professeure guide l'exercice d'une participante" },
      { img: "/images/kanji-teacher-shows.jpg", alt: "La professeure montre un caractère terminé" },
      { img: "/images/kanji-brush-closeup.jpg", alt: "Gros plan d'un pinceau sur le papier d'exercice" },
      { img: "/images/kanji-teacher-check.jpg", alt: "La professeure vérifie les feuilles d'exercice" },
      { img: "/images/kanji-studio.jpg", alt: "Le studio lumineux et sa longue table commune" },
    ],
    galleryNote: "Photos des cours d'essai de la professeure ; le studio peut varier selon la date.",
    langTag: "Cours en anglais",
    includedShort: "Cours avec la professeure · Tout le matériel · Votre œuvre + support",
    cancellation: "Les jours se comptent jusqu'à la date du cours, à l'heure du Japon. Les changements de date suivent le même barème, s'il reste de la place à une autre date. Le studio est loué à l'heure : en cas de retard, l'exercice est raccourci, le cours n'est pas prolongé. Si la professeure doit annuler, vous êtes prévenu avant 17 h la veille et intégralement remboursé.",
    highlights: [
      { icon: "chat", title: "Des kanji choisis pour votre prénom", body: "Dites-nous ce que signifie votre prénom. La professeure propose des caractères qui portent ce sens, et vous choisissez celui qui vous ressemble." },
      { icon: "photo", title: "Une œuvre à emporter", body: "Votre œuvre finale sur un shikishi, scellée d'un cachet rouge et posée sur un support en bois, réalisée et remise le jour même." },
      { icon: "group", title: "Rien que votre groupe", body: "Les cours ne sont pas partagés avec d'autres clients : une à quatre personnes, une professeure, une longue table." },
    ],
    included: ["Un cours de deux heures mené par la professeure en anglais simple", "Tout le matériel : pinceau, encre, pierre à encre, feutre et papier d'exercice, plus un tablier", "Votre œuvre finale sur un shikishi, avec un support en bois pour l'exposer", "Le cachet rouge sur votre œuvre et du temps pour les photos à la fin", "Taxes comprises : rien n'est ajouté le jour même"],
    notIncluded: ["Le trajet jusqu'au studio (rendez-vous sur place)", "Un guide-interprète : la professeure donne le cours en anglais", "Les cartes et tirages de la professeure, en vente au studio si vous le souhaitez"],
    schedule: [
      { time: "10:30", title: "Accueil", body: "Tablier enfilé, courte présentation du pinceau, de l'encre et du papier." },
      { time: "10:40", title: "Exercice au pinceau", body: "Les traits de base : pression, vitesse et l'arrêt en fin de ligne.", img: "/images/kanji-brush-closeup.jpg" },
      { time: "11:00", title: "Choisir votre kanji", body: "À partir de votre prénom et de son sens, la professeure propose des caractères et explique chacun ; vous choisissez.", img: "/images/kanji-teacher-check.jpg" },
      { time: "11:15", title: "Style et exercice", body: "Choisissez un style, classique ou ludique, et exercez-vous jusqu'à ce qu'il vous plaise.", img: "/images/kanji-teacher-demo.jpg" },
      { time: "11:45", title: "Votre œuvre finale", body: "Tracez la version finale sur un shikishi.", img: "/images/kanji-brush-focus.jpg" },
      { time: "12:15", title: "Cachet et photos", body: "Le cachet rouge est apposé, puis photos avec votre œuvre avant de la poser sur son support.", img: "/images/kanji-guests-works.jpg" },
      { time: "12:30", title: "Fin du cours" },
    ],
    venue: {
      known: ["Un studio de location à Shinjuku, Tokyo ; l'adresse exacte arrive avec votre confirmation", "Tables et chaises ; une salle lumineuse avec une longue table commune", "Rendez-vous avec la professeure au studio 5 minutes avant le début", "L'encre tache : portez des vêtements sans importance (tabliers fournis)"],
      afterBooking: ["Le nom et l'adresse du studio", "L'itinéraire depuis la gare la plus proche", "Le contact de la professeure pour le jour même"],
      img: "/images/kanji-studio.jpg", alt: "Le studio et sa longue table commune",
    },
    notesLabel: "Le prénom de chacun et sa signification si vous la connaissez, et tout ce que la professeure doit savoir (facultatif)",
    notesHint: "ex. Emma — « entière, universelle » ; Liam — « protecteur résolu ». L'un de nous est gaucher…",
    flow: [
      { title: "Choisissez une date et envoyez votre demande", body: "Choisissez une des dates publiées et une heure de début. Ajoutez le prénom de chacun et sa signification si vous la connaissez." },
      { title: "Nous répondons sous 24 heures", body: "Avec la disponibilité du cours ce jour-là, le prix et les conditions." },
      { title: "Réglez pour confirmer", body: "La réservation est confirmée à réception de votre paiement ; les conditions d'annulation commencent alors. Nous vous demandons ensuite ce dont la professeure a besoin : le prénom et le sens de chacun, la nationalité et un téléphone pour le jour même." },
    ],
    faq: [
      { q: "Faut-il de l'expérience ?", a: "Non. Le cours commence par les traits de base et la professeure adapte le rythme à votre groupe." },
      { q: "Comment choisir des kanji pour un prénom non japonais ?", a: "Par le sens. Dites-nous ce que signifie votre prénom, autant que vous le sachiez ; la professeure propose des caractères qui le portent et explique chacun. Si vous préférez ne pas utiliser votre prénom, choisissez un mot : lumière, rêve, courage." },
      { q: "Qu'est-ce que je rapporte ?", a: "Votre œuvre finale sur un shikishi, scellée d'un cachet rouge, et un support en bois pour l'exposer." },
      { q: "Dans quelle langue se déroule le cours ?", a: "En anglais : la professeure donne le cours elle-même en anglais simple. Aucun guide-interprète n'accompagne ce cours." },
      { q: "Les enfants peuvent-ils participer ?", a: "Dès 10 ans, car on utilise de la vraie encre. Ils paient le tarif adulte." },
      { q: "Je voyage seul(e). Puis-je participer ?", a: "Oui. Un cours pour une personne est facturé comme pour deux ; l'encadré de réservation affiche le total quand vous choisissez une personne." },
      { q: "Comment s'habiller ?", a: "Avec des vêtements que l'encre peut tacher. Des tabliers sont fournis." },
      { q: "Comment se passe la réservation ?", a: "Choisissez une date publiée et envoyez une demande ; nous répondons sous 24 heures avec le prix et les conditions. La demande est gratuite. La réservation est confirmée lorsque vous réglez via le lien envoyé, et les conditions d'annulation commencent alors." },
      { q: "Et si nous sommes en retard ?", a: "Le studio est loué à l'heure : le cours se termine à l'heure prévue et l'exercice est raccourci. Prévenez-nous dès que vous savez que vous serez en retard." },
      { q: "Le transport est-il compris ?", a: "Non. Vous retrouvez la professeure au studio de Shinjuku ; l'adresse et l'itinéraire arrivent avec votre confirmation." },
    ],
    whatYoullDo: ["Apprendre les traits de base au pinceau", "Choisir des kanji qui portent le sens de votre prénom", "Tracer votre œuvre finale sur un shikishi", "L'emporter scellée, sur son support"],
    master: { title: "Votre professeure", bio: "Marie enseigne le fude-moji, une calligraphie expressive au pinceau, à Tokyo et donne tous les cours elle-même.", quote: "" },
    itinerary: ["10:30 — Accueil", "10:40 — Exercice au pinceau", "11:00 — Choisir votre kanji", "11:15 — Style et exercice", "11:45 — Votre œuvre finale", "12:15 — Cachet et photos"],
    goodToKnow: ["Dès 10 ans ; les enfants paient le tarif adulte.", "Vêtements sans importance ; tabliers fournis.", "Cours en anglais simple."],
    story: { heading: "Pourquoi un prénom en kanji", body: "Les kanji portent un sens, pas seulement un son. Choisir des caractères pour un prénom, c'est ainsi que beaucoup de parents japonais nomment leurs enfants — et le souvenir devient quelque chose qui parle vraiment de vous." },
  },
  {
    slug: "sushi-masterclass", city: "tokyo", category: "sushi",
    title: "Masterclass de sushi Edo-mae",
    tagline: "Façonnez des nigiri avec un chef de troisième génération, à son propre comptoir",
    duration: "2 h 30", price: "¥45,000", group: "Privé · jusqu'à 6", ages: "Dès 8 ans", area: "Tokyo (quartier de Tsukiji)",
    img: "/images/exp-sushi.jpg", alt: "Comptoir omakase en bois de hinoki, silencieux",
    gallery: [{ img: "/images/cat-sushi.jpg", alt: "Chef sushi tranchant du poisson sur une planche en bois" }],
    whatYoullDo: [
      "Prenez place au comptoir du chef, fermé au public pour votre séance.",
      "Apprenez à façonner le shari, assaisonner le neta et presser le nigiri, corrigé de sa main.",
      "Goûtez chaque pièce à l'instant où elle est faite, comme le sushi Edo-mae doit se manger.",
      "Terminez par la sélection du chef, servie à vous en tant que ses invités.",
    ],
    master: { quote: "Mon grand-père tenait mes mains au-dessus du riz. Aujourd'hui, je tiens les vôtres.", title: "Un chef sushi Edo-mae de troisième génération", bio: "Formé par son père et son grand-père au comptoir même où vous vous tiendrez, dans un quartier façonné par l'ancien marché de Tsukiji. Il prend rarement des élèves ; cette séance est l'exception. Le nom de son établissement est communiqué une fois votre réservation confirmée." },
    itinerary: ["10:00 — Rendez-vous avec votre guide-interprète près du lieu", "10:15 — Présentations, tablier, travail du couteau et shari", "11:15 — Façonnage des nigiri au comptoir", "12:00 — Dégustation et plat final du chef", "12:30 — Fin de l'expérience"],
    goodToKnow: ["Se déroule le matin avant l'ouverture ; les jours exacts dépendent de l'emploi du temps du chef.", "Le poisson cru est au cœur de la séance — signalez-nous vos allergies et nous adapterons.", "Séance pratique, debout la plupart du temps ; tabliers fournis.", "Photos bienvenues ; nous demandons de laisser la devanture et l'enseigne hors champ."],
    story: { heading: "L'histoire du sushi Edo-mae", body: "Edo-mae — « devant Edo » — désignait autrefois le poisson tiré de la baie de Tokyo, salé, pressé ou saisi pour tenir une journée sans glace. Les techniques ont survécu à la réfrigération parce qu'elles sont meilleures, pas parce qu'elles sont anciennes. Ce que vous apprenez à ce comptoir, c'est ce répertoire : vinaigre, sel, kombu et temps, appliqués pièce par pièce." },
  },
  {
    slug: "sumo-morning-practice", city: "tokyo", category: "sumo",
    title: "L'entraînement matinal de sumo, de l'intérieur",
    tagline: "Au bord du ring d'une écurie en activité, pendant que la journée d'entraînement se déroule",
    duration: "2 h", price: "¥38,000", group: "Petit groupe · jusqu'à 8", ages: "Dès 10 ans", area: "Tokyo (quartier de Ryogoku)",
    img: "/images/exp-sumo.jpg", alt: "Lutteurs de sumo à l'entraînement sur le ring d'une écurie de Tokyo",
    gallery: [{ img: "/images/cat-sumo.jpg", alt: "Lutteurs de sumo lors de la cérémonie d'entrée sur le ring" }],
    whatYoullDo: [
      "Entrez dans une écurie de sumo en activité avec votre guide, avant le réveil de la ville.",
      "Observez le keiko — l'entraînement du matin — depuis des places sur tatami, à quelques mètres du ring.",
      "Comprenez le sens de chaque exercice et de chaque rituel au moment où il se produit, dans votre langue.",
      "Rencontrez brièvement les lutteurs après l'entraînement, selon leur emploi du temps.",
    ],
    master: { quote: "L'entraînement n'est pas un spectacle. Mais ce matin, la porte vous est ouverte.", title: "Une écurie de sumo du quartier de Ryogoku", bio: "L'écurie forme des lutteurs classés depuis des décennies dans le quartier historique du sumo à Tokyo. Les visites sont limitées pour ne jamais perturber l'entraînement ; votre guide vous expliquera l'étiquette avant d'entrer. Le nom de l'écurie est communiqué une fois votre réservation confirmée." },
    itinerary: ["07:30 — Rendez-vous avec votre guide-interprète à Ryogoku", "07:45 — Rappel de l'étiquette, entrée dans l'écurie", "08:00 — Entraînement du matin, observé depuis les tatamis", "09:15 — Bref salut aux lutteurs (selon l'emploi du temps)", "09:30 — Fin de l'expérience"],
    goodToKnow: ["L'entraînement suit le calendrier des tournois ; certaines semaines sont indisponibles.", "Le silence est de rigueur pendant l'entraînement ; votre guide traduit à voix basse.", "Vous serez assis sur tatami jusqu'à 90 minutes ; coussins fournis.", "Tenue sobre ; pas de flash à l'intérieur de l'écurie."],
    story: { heading: "Le monde d'une écurie de sumo", body: "Le sumo professionnel se vit, il ne se joue pas. Les lutteurs partagent un toit, une cuisine et une hiérarchie stricte, et le ring du matin est l'endroit où tout cela devient visible — les jeunes balaient le dohyo, les anciens prennent les derniers combats, les plus durs. Voir le keiko, c'est voir toute la société du sport d'un coup." },
  },
  {
    slug: "kimono-photo-walk", city: "tokyo", category: "kimono",
    title: "Habillage en kimono et promenade photo dans un jardin",
    tagline: "Habillé(e) par une styliste professionnelle, puis une flânerie dans un jardin classique",
    duration: "3 h", price: "¥40,000", group: "Privé · jusqu'à 4", ages: "Tous âges", area: "Tokyo (quartier de jardins traditionnels)",
    img: "/images/exp-kimono.jpg", alt: "Femme en kimono rouge au bord d'un bassin à carpes dans un jardin japonais",
    gallery: [{ img: "/images/cat-kimono.jpg", alt: "Kimono ancien en soie à motif de faisan et de pivoine" }],
    whatYoullDo: [
      "Choisissez dans une garde-robe de kimonos en soie assortis à la saison.",
      "Faites-vous habiller dans les règles — chaque couche, pli et nœud — par une styliste professionnelle.",
      "Parcourez un jardin de promenade classique pendant que votre guide en raconte la conception et l'histoire.",
      "Prenez le temps de photographier aux meilleurs points de vue du jardin.",
    ],
    master: { quote: "Un kimono ne se porte pas — il se construit. Et je vais le construire sur vous.", title: "Une styliste de kimono professionnelle", bio: "Elle habille des clientes pour des mariages, des cérémonies et le cinéma depuis plus de vingt ans, et compose chaque ensemble selon la personne et la saison plutôt que de le tirer d'un portant de costumes. L'adresse de son atelier est communiquée une fois votre réservation confirmée." },
    itinerary: ["10:00 — Rendez-vous avec votre guide-interprète à l'atelier", "10:15 — Choix du kimono et habillage", "11:15 — Promenade dans le jardin et photos", "12:45 — Retour, changement de tenue, thé", "13:00 — Fin de l'expérience"],
    goodToKnow: ["Kimonos disponibles dans une large gamme de tailles ; indiquez-nous votre taille à l'avance.", "Marcher confortablement fait partie de l'expérience ; chaussettes tabi fournies.", "Par temps de pluie, la promenade passe par les allées couvertes et le pavillon de thé du jardin.", "Un photographe professionnel peut être ajouté sur demande."],
    story: { heading: "Pourquoi l'habillage compte", body: "Un kimono ne s'enfile pas ; il se construit — couche sur couche, ajusté au corps jusqu'à ce que la silhouette soit juste. Bien porté, il change la façon dont on se tient et marche, et c'est exactement pour cela que le jardin vient après le vestiaire. Le jardin a été conçu pour des gens qui avancent au rythme d'un kimono." },
  },
  {
    slug: "katana-forge-visit", city: "tokyo", category: "swordsmith",
    title: "Katana : visite de la forge d'un maître forgeron",
    tagline: "Regardez un forgeron agréé plier l'acier selon la tradition",
    duration: "3 h", price: "¥90,000", group: "Privé · jusqu'à 4", ages: "Dès 12 ans", area: "Grand Tokyo (quartier d'ateliers)",
    img: "/images/cat-sword.jpg", alt: "Lame de katana polie, photographiée sur fond noir",
    gallery: [],
    whatYoullDo: [
      "Rendez-vous avec votre guide dans une forge en activité rarement ouverte aux visiteurs.",
      "Regardez l'acier tamahagane chauffé, martelé et plié sur l'enclume.",
      "Tenez des lames finies et apprenez comment le polisseur révèle le hamon.",
      "Posez toutes vos questions au forgeron — votre guide traduit l'échange entier.",
    ],
    master: { quote: "L'acier se souvient de chaque coup. Venez le regarder se souvenir.", title: "Un forgeron de sabres japonais agréé", bio: "L'un des rares forgerons autorisés à forger des nihonto aujourd'hui, il travaille dans la forge au charbon traditionnelle avec un seul apprenti. Les jours de forge sont irréguliers ; les dates sont confirmées individuellement. L'adresse de sa forge est communiquée une fois votre réservation confirmée." },
    itinerary: ["09:30 — Rendez-vous avec votre guide-interprète ; trajet ensemble jusqu'à la forge", "10:30 — Présentation de la forge et de ses outils", "11:00 — Démonstration de forge sur l'enclume", "12:00 — Manipulation des lames, questions au forgeron", "12:30 — Fin de l'expérience (retour avec votre guide)"],
    goodToKnow: ["La forge est chaude et bruyante pendant les démonstrations ; protections auditives fournies.", "Chaussures fermées et vêtements en fibres naturelles obligatoires près du feu.", "Les dates dépendent du calendrier de production du forgeron — réservez tôt.", "Les lames ne se manipulent que sous la supervision directe du forgeron."],
    story: { heading: "Mille ans dans une seule courbe", body: "Le sabre japonais survit parce que sa fabrication n'a jamais été simplifiée. Le même acier est encore fondu à partir de sable ferrugineux, plié pour chasser les impuretés, et trempé dans l'eau pour créer la courbe et le hamon en un seul instant de risque. Chaque forgeron agréé en activité aujourd'hui est une ligne directe vers cette méthode ininterrompue." },
  },
  {
    slug: "anime-nail-art-session", city: "tokyo", category: "anime-nail-art",
    title: "Séance de nail art anime",
    tagline: "Votre personnage préféré, peint par une nail artist de Tokyo",
    duration: "2 h", price: "¥18,000", group: "Privé · jusqu'à 2", ages: "Tous âges", area: "Tokyo (Akihabara / Harajuku)",
    img: "/images/cat-nail.jpg", alt: "Rue d'Akihabara sous les néons, la nuit",
    gallery: [],
    whatYoullDo: [
      "Partagez à l'avance vos personnages ou visuels préférés avec l'artiste.",
      "Regardez de minuscules illustrations peintes à la main prendre forme, ongle après ongle.",
      "Discutez avec l'artiste de la culture du nail art et du fan art à Tokyo pendant qu'elle travaille.",
      "Repartez avec un gel art durable — et les conseils d'entretien de l'artiste.",
    ],
    master: { quote: "Apportez-moi votre personnage préféré. Je le ferai tenir sur huit millimètres.", title: "Une nail artist de Tokyo spécialisée dans les personnages", bio: "Son carnet est rempli de fans qui prennent l'avion pour son travail de personnages peints à la main, des franchises classiques aux sorties de la saison. Elle peint à main levée avec des pinceaux plus fins qu'une mine de crayon. L'adresse de son salon est communiquée une fois votre réservation confirmée." },
    itinerary: ["14:00 — Rendez-vous avec votre guide-interprète au salon", "14:10 — Consultation autour de vos références", "14:30 — Séance de peinture", "15:50 — Couche de finition et entretien", "16:00 — Fin de l'expérience"],
    goodToKnow: ["Envoyez des images de référence à la réservation pour que l'artiste prépare les couleurs.", "Le gel art tient en général trois à quatre semaines avec un usage normal.", "Les motifs complexes peuvent prolonger la séance ; la durée est confirmée à l'avance.", "Cette expérience est dans une gamme de prix plus légère que nos masterclasses — elle n'en est pas moins artisanale."],
    story: { heading: "Un fan art à porter", body: "Le nail art a grandi aux côtés de la culture des personnages au Japon, et à Tokyo les deux ont fusionné en un genre à part : la micro-illustration, peinte sur une toile mobile plus petite qu'un timbre. Les meilleures artistes sont réservées des semaines à l'avance par les habitants. Cette séance vous ouvre l'un de ces fauteuils." },
  },
  {
    slug: "evening-with-geiko", city: "kyoto", category: "geisha", bookingType: "request", status: "live",
    title: "Banquet ozashiki avec maiko et geiko",
    tagline: "Deux heures privées à Kyoto avec une geiko ou une maiko. Partagez un dîner japonais de saison, conversez à table, assistez à une danse traditionnelle et jouez aux jeux ozashiki — avec un guide-interprète tout au long de la soirée, en français, anglais ou espagnol.",
    duration: "2 h", price: "¥219,800", priceUnit: "group", group: "Privé · 2 à 40 convives", ages: "Tous âges", area: "Kyoto (Gion / Higashiyama)",
    img: "/images/geiko-photo-together.jpg", alt: "Deux convives et une maiko sourient pour une photo souvenir dans une salle privée de Kyoto",
    gallery: [
      { img: "/images/geiko-conversation.jpg", alt: "La conversation autour du dîner, l'interprète assurant les deux sens", caption: "La conversation autour du dîner, l'interprète assurant les deux sens" },
      { img: "/images/geiko-maiko-seated.jpg", alt: "Une maiko s'installe à votre table", caption: "Une maiko s'installe à votre table" },
      { img: "/images/geiko-dance.jpg", alt: "Une danse devant le paravent doré", caption: "Une danse devant le paravent doré" },
      { img: "/images/geiko-dinner-course.jpg", alt: "Le dîner japonais en plusieurs services (le menu change avec la saison)", caption: "Le dîner japonais en plusieurs services (le menu change avec la saison)" },
      { img: "/images/geiko-maiko-smile.jpg", alt: "Une maiko dans la salle privée", caption: "Une maiko dans la salle privée" },
      { img: "/images/geiko-pouring.jpg", alt: "Votre hôtesse vous sert ; posez-lui toutes vos questions", caption: "Votre hôtesse vous sert ; posez-lui toutes vos questions" },
      { img: "/images/geiko-game-table.jpg", alt: "Les jeux d'ozashiki à table", caption: "Les jeux d'ozashiki à table" },
      { img: "/images/geiko-game-toratora.jpg", alt: "Tora-tora, un pierre-feuille-ciseaux joué de tout le corps", caption: "Tora-tora, un pierre-feuille-ciseaux joué de tout le corps" },
      { img: "/images/geiko-room-upstairs.jpg", alt: "Une salle à l'étage, construite comme une maison de thé de Gion", caption: "Une salle à l'étage, construite comme une maison de thé de Gion" },
      { img: "/images/geiko-room-garden.jpg", alt: "Une salle au rez-de-chaussée donnant sur le jardin intérieur", caption: "Une salle au rez-de-chaussée donnant sur le jardin intérieur" },
    ],
    cancellation: "Les jours se comptent jusqu'à la date de l'expérience, heure du Japon. Les changements de date suivent le même barème, et la réduction du nombre de convives applique les frais aux places libérées ; les remboursements se font par le moyen de paiement utilisé. Si aucune geiko ou maiko ne peut être réservée pour votre date, vous êtes intégralement remboursé, quel que soit le moment.",
    whatYoullDo: [
      "Installez-vous dans votre propre salon de banquet — jamais partagé avec d'autres convives.",
      "Dînez d'une cuisine de Kyoto de saison pendant que geiko et maiko rejoignent votre table pour converser.",
      "Assistez à une danse exécutée à portée de main, puis essayez ensemble les jeux de salon ozashiki.",
      "Terminez par des photos souvenir avec vos hôtesses.",
    ],
    master: { quote: "Pour un soir, cette pièce est la vôtre. Venez, parlons.", title: "Geiko et maiko des hanamachi de Kyoto", bio: "Votre soirée est animée par des geiko ou maiko en activité du monde des fleurs et des saules de Kyoto, engagées spécialement pour votre date. Le lieu est une maison de banquet privée du quartier de Gion / Higashiyama ; son nom et son adresse sont communiqués une fois votre réservation confirmée." },
    itinerary: ["10 min avant — Arrivée au lieu avec votre guide (adresse dans votre confirmation)", "0:00 — Bienvenue dans votre salon privé ; le banquet commence", "0:30 — Geiko et maiko rejoignent votre table ; conversation pendant le dîner", "1:15 — Danse et jeux de salon ozashiki", "1:50 — Photos souvenir", "2:00 — Fin de la soirée"],
    goodToKnow: [
      "Tous les jours sauf pendant les fêtes du Nouvel An, débuts de 12:00 à 20:30 — réservez au moins 3 jours à l'avance (clôture à 17 h, heure du Japon).",
      "Trois formules, chacune tarifée pour 2 convives : Select dès ¥219,800, Signature (shamisen en direct) dès ¥379,800, Private Reserve (deux artistes et shamisen) dès ¥498,000. Chaque convive supplémentaire jusqu'à 5 : ¥39,800 ; six et plus sur demande.",
      "Tarifs haute saison du 15 mars au 31 mai et du 1er octobre au 30 novembre (Select dès ¥249,800 ; convive supplémentaire ¥49,800).",
      "Enfants : gratuit sans repas jusqu'à 2 ans, demi-tarif adulte de 3 à 11 ans, tarif adulte avec menu complet dès 12 ans.",
      "Allergies et régimes particuliers pris en compte — signalez-les à la réservation.",
      "Envie de musique en direct ou d'une salle plus animée ? Choisissez Signature (une jikata au shamisen, en direct) ou Private Reserve (deux geiko ou maiko et la jikata).",
    ],
    story: { heading: "Le monde du karyukai", body: "Le « monde des fleurs et des saules » de Kyoto repose depuis trois siècles sur la recommandation et la confiance. Une geiko n'est pas une artiste à louer mais une artiste dont les soirées se prolongent par les relations entre maisons de thé et clients fidèles. Être assis dans cette pièce, avec une conversation qui coule dans votre propre langue, est l'accès le plus rare que Kyoto puisse offrir." },
    availabilityNote: "Fermé pendant les fêtes du Nouvel An.",
    interactionTime: "environ 1 h 45",
    includedShort: "Salle privée · Repas et boissons · Guide-interprète (FR / EN / ES)",
    planText: {
      select: { label: "Select", name: "Private Geisha Evening", performers: "Une geiko ou maiko", blurb: "La soirée essentielle ; la danse est accompagnée d'une musique enregistrée." },
      signature: { label: "Signature", name: "Private Geisha Evening with Live Shamisen", performers: "Geiko ou maiko + shamisen en direct", blurb: "Une geiko ou maiko, rejointe par une jikata au shamisen, en direct." },
      reserve: { label: "Private Reserve", name: "The Complete Geisha Evening", performers: "Deux artistes + shamisen en direct", blurb: "Deux geiko ou maiko et une jikata au shamisen. La version la plus complète de la soirée." },
    },
    galleryNote: "La salle et les plats photographiés sont donnés à titre d'exemple ; ils varient selon la date et la saison.",
    highlights: [
      { icon: "group", title: "La salle est à vous", body: "Un salon de banquet privé réservé à votre groupe, jamais partagé avec d'autres convives." },
      { icon: "chat", title: "Une conversation, pas seulement un spectacle", body: "Geiko et maiko s'installent à votre table pour discuter, dansent à portée de main, puis jouent avec vous aux jeux d'ozashiki." },
      { icon: "interpreter", title: "Posez toutes vos questions", body: "Un guide-interprète porte la conversation dans les deux sens : vos questions atteignent la salle et les réponses vous reviennent." },
    ],
    included: [
      "Une salle privée en tatami pour votre groupe : à l'étage, des salles construites comme une maison de thé de Gion ; au rez-de-chaussée, des salles sur le jardin intérieur",
      "Un dîner japonais en plusieurs services : obanzai de saison, sashimi, un plat de viande, tempura, riz et soupe, dessert (selon le marché)",
      "Boissons à volonté toute la soirée : bière, saké, shochu, vin, highballs, umeshu et boissons sans alcool",
      "Une geiko ou une maiko à votre table : conversation, une danse et les jeux de salon Konpira Funefune et Tora-tora",
      "Photos et vidéos bienvenues, danse comprise — sans flash ni trépied, votre guide explique les règles de la maison —, plus des photos souvenir avec votre hôtesse",
      "Quatre menus au choix : le kaiseki classique, végétarien (avec option sans bouillon de poisson), sans gluten ou un set de steak de wagyu, viande uniquement ; précisez-le lors de votre demande de date",
      "Un guide-interprète — français, anglais ou espagnol, à votre choix — à vos côtés de l'arrivée au départ : il vous accueille, explique Kyoto et la culture des quartiers de geishas, la danse et chaque plat, et porte la conversation avec votre hôtesse dans les deux sens",
      "Taxes et service compris : rien n'est ajouté le jour même",
    ],
    notIncluded: [
      "Interprètes dans une autre langue que le français, l'anglais ou l'espagnol : demandez-le lors de votre demande de date",
      "Les groupes de six convives et plus font l'objet d'un devis individuel : jusqu'à 40 convives, au-delà sur demande",
    ],
    schedule: [
      { time: "17:50", title: "Arrivée avec votre guide", body: "L'adresse figure dans votre confirmation. Votre guide vous attend à proximité et vous accompagne à l'intérieur." },
      { time: "18:00", title: "Votre salle privée", body: "Vous prenez place sur les tatamis ; les premiers plats et les boissons arrivent.", img: "/images/geiko-room-upstairs.jpg" },
      { time: "18:15", title: "Votre geiko ou maiko arrive", body: "Elle rejoint la table directement depuis l'okiya et reste environ 1 h 45. Conversation autour du dîner, l'interprète assurant les deux sens.", img: "/images/geiko-conversation.jpg" },
      { time: "19:00", title: "La danse", body: "Une danse devant le paravent doré : sur musique enregistrée avec Select, au shamisen en direct avec Signature et Private Reserve. Les appareils photo sont les bienvenus.", img: "/images/geiko-dance.jpg" },
      { time: "19:15", title: "Jeux d'ozashiki", body: "Konpira Funefune, un jeu de rythme, et Tora-tora, un pierre-feuille-ciseaux joué de tout le corps.", img: "/images/geiko-game-toratora.jpg" },
      { time: "19:50", title: "Photographies", body: "Photos souvenir avec votre hôtesse.", img: "/images/geiko-photo-together.jpg" },
      { time: "20:00", title: "Fin de la soirée" },
    ],
    venue: {
      known: ["Gion / Higashiyama, Kyoto : à environ 8 minutes à pied de la gare de Gion-Shijo (ligne Keihan)", "Une salle privée dans une maison de cuisine traditionnelle : salles de style maison de thé à l'étage, salles sur jardin au rez-de-chaussée", "On s'assied sur tatami", "Rendez-vous sur place : aucun transfert n'est organisé"],
      afterBooking: ["Le nom et l'adresse de la maison", "Un plan et l'itinéraire à pied depuis la gare", "Le contact de votre guide pour la soirée"],
      img: "/images/geiko-room-garden.jpg", alt: "Une salle en tatami au rez-de-chaussée donnant sur le jardin intérieur",
    },
    faq: [
      { q: "Sera-ce une geiko ou une maiko ?", a: "Une geiko ou une maiko est réservée pour votre date. La maison ne peut accepter ni la demande d'une personne précise, ni celle d'une maiko plutôt qu'une geiko ; si vous avez une préférence, nous la transmettrons sans la garantir." },
      { q: "Combien de temps avant la confirmation de la date ?", a: "Nous répondons sous 24 heures avec la disponibilité de la salle, le prix et les conditions ; cette réponse n'est pas encore une réservation. La réservation est confirmée lorsque vous acceptez ces conditions en réglant via le lien que nous envoyons ; les conditions d'annulation s'appliquent à partir de ce moment. La maison réserve ensuite votre geiko ou maiko : la demande formelle est déposée au plus tard 14 jours avant votre date (immédiatement pour les dates plus proches). Si aucune n'est disponible, vous êtes intégralement remboursé." },
      { q: "Peut-on ajouter du shamisen en direct ou une seconde hôtesse ?", a: "Oui, c'est à cela que servent les formules. Signature ajoute une jikata au shamisen, en direct ; Private Reserve réunit deux geiko ou maiko et la jikata. Choisissez la formule lors de votre demande de date." },
      { q: "Peut-on photographier pendant la danse ?", a: "Oui. Photos et vidéos sont les bienvenues à tout moment, danse comprise — sans flash ni trépied, selon les règles de la maison que votre guide explique —, et un temps est réservé en fin de soirée aux photos souvenir avec votre hôtesse." },
      { q: "Les boissons sont-elles comprises ? Y a-t-il un code vestimentaire ?", a: "Les boissons sont à volonté (bière, saké, shochu, vin, highballs, boissons sans alcool) et comprises, de même que taxes et service. Il n'y a pas de code vestimentaire." },
      { q: "Notre hôtesse mange-t-elle et boit-elle avec nous ?", a: "Généralement non. Beaucoup de maiko ont moins de vingt ans et, par tradition, geiko et maiko ne mangent pas à table : elles servent, conversent, dansent et jouent. N'insistez pas pour leur offrir à manger ou à boire ; c'est la seule règle d'étiquette que votre guide mentionnera." },
      { q: "Les régimes et allergies sont-ils pris en compte ?", a: "Oui. Choisissez entre le kaiseki classique, un menu végétarien (le bouillon de poisson peut être omis), un menu sans gluten ou un set de steak de wagyu pour ceux qui ne mangent pas de poisson (salade, steak et riz, servis en une fois, donc à un rythme différent des autres menus). Pour les allergies ou les restrictions religieuses, indiquez les ingrédients que vous ne pouvez pas manger et la cuisine les remplace dans le menu ; il n'existe pas de menu halal ou casher certifié, et la contamination croisée ne peut être totalement exclue. Les substitutions concernent les allergies et les impératifs religieux, pas les préférences. Précisez-le dans votre demande ; la réponse de la cuisine vous parvient avec les conditions, avant tout paiement." },
      { q: "Les enfants sont-ils les bienvenus ? Que paient-ils ?", a: "Oui. Les enfants de 2 ans et moins participent gratuitement sans repas ; de 3 à 11 ans, la moitié du tarif adulte ; à partir de 12 ans, le tarif adulte. Dès 3 ans, ils reçoivent le même menu que les adultes : il n'y a pas de menu enfant. Comptez tout le monde dans le nombre de convives et indiquez l'âge des enfants dans votre demande ; le devis envoyé applique la réduction." },
      { q: "Combien de temps à l'avance faut-il réserver ?", a: "Au plus tard sept jours avant, avant 17 h heure du Japon ; 10 à 14 jours à l'avance est la fenêtre confortable, et le printemps et l'automne (mars–avril, octobre–novembre) se remplissent en premier. Pendant le Miyako Odori (avril), la maison ne peut parfois confirmer que peu avant la date. Le créneau horaire définitif est confirmé avec la réponse de disponibilité." },
    ],
  },
  {
    slug: "tea-ceremony-with-master", city: "kyoto", category: "tea-ceremony",
    title: "Cérémonie du thé avec une maîtresse de thé",
    tagline: "Une heure paisible de temae dans une maison de thé de Kyoto, bol après bol",
    duration: "1 h 30", price: "¥30,000", group: "Privé · jusqu'à 6", ages: "Tous âges", area: "Kyoto (quartier des temples)",
    img: "/images/craft-hands.jpg", alt: "Hôtesse de cérémonie du thé posant un bol sur le tatami devant des invités assis",
    gallery: [{ img: "/images/cat-tea.jpg", alt: "Hôtesse préparant le matcha lors d'une réunion de thé en plein air" }],
    whatYoullDo: [
      "Entrez dans une maison de thé en activité par son allée de jardin, comme les invités depuis des siècles.",
      "Assistez à un temae complet — la chorégraphie du charbon, de l'eau, du fouet et du bol.",
      "Fouettez votre propre bol de matcha sous la direction de la maîtresse.",
      "Apprenez comment les ustensiles, le rouleau et les fleurs sont choisis pour ce jour et cette saison.",
    ],
    master: { quote: "Une fois, une rencontre. Ce bol de thé ne se reproduira jamais.", title: "Une maîtresse de thé de Kyoto en activité", bio: "Diplômée de l'une des grandes écoles de thé, elle pratique depuis plus de trente ans et reçoit tout au long de l'année. Sa maison de thé se trouve près de l'un des quartiers de temples de Kyoto ; l'adresse exacte est communiquée une fois votre réservation confirmée." },
    itinerary: ["10:00 — Rendez-vous avec votre guide-interprète près de la maison de thé", "10:10 — Allée du jardin, purification et entrée dans la pièce", "10:20 — Temae de la maîtresse, premiers bols et douceurs", "10:50 — Fouettez votre propre bol ; examen des ustensiles et conversation", "11:30 — Fin de l'expérience"],
    goodToKnow: ["Assis sur tatami ; on peut étendre les jambes et des tabourets bas sont disponibles.", "Les chaussettes blanches sont appréciées ; nous vous le rappellerons la veille.", "Les douceurs ne contiennent aucun produit animal ; autres besoins pris en compte sur demande.", "Mouvements et photos s'interrompent pendant le temae lui-même — votre guide vous fera signe."],
    story: { heading: "Une fois, une rencontre", body: "Ichigo ichie — l'idée que cette réunion, avec ces personnes, n'a lieu qu'une seule fois — est le cœur de la cérémonie du thé. Tout dans la pièce répond au jour : le rouleau, la fleur, la glaçure du bol face à la saison. Le rituel n'est pas un spectacle mais une attention, offerte aux invités un bol à la fois." },
  },
  {
    slug: "kimono-higashiyama-walk", city: "kyoto", category: "kimono",
    title: "Kimono et promenade aux lanternes dans Higashiyama",
    tagline: "Vêtu(e) de soie, puis dans les ruelles les plus chargées d'histoire de Kyoto à l'heure dorée",
    duration: "3 h", price: "¥40,000", group: "Privé · jusqu'à 4", ages: "Tous âges", area: "Kyoto (Higashiyama)",
    img: "/images/cat-kimono.jpg", alt: "Kimono ancien en soie à motif de faisan et de pivoine",
    gallery: [{ img: "/images/city-kyoto.jpg", alt: "Rue Yasaka-dori bordée de lanternes à l'aube, avec la pagode de Yasaka" }],
    whatYoullDo: [
      "Faites-vous habiller de soie de saison par une professionnelle du kitsuke de Kyoto.",
      "Parcourez les ruelles pavées de Higashiyama au moment où les lanternes s'allument.",
      "Écoutez l'histoire des rues de la pagode racontée par votre guide, chemin faisant.",
      "Faites une pause photo là où la foule s'éclaircit et où la lumière est la plus belle.",
    ],
    master: { quote: "Marchez dans ces ruelles en soie à l'heure des lanternes — vous verrez pourquoi nous nous habillons encore ainsi.", title: "Une professionnelle du kitsuke (habillage en kimono) de Kyoto", bio: "Formée à l'habillage de cérémonie pour les saisons de fêtes de Kyoto, elle choisit dans une garde-robe de soies anciennes et contemporaines plutôt que dans du polyester de location. Son atelier de Higashiyama est à quelques pas du parcours ; l'adresse est communiquée une fois votre réservation confirmée." },
    itinerary: ["15:30 — Rendez-vous avec votre guide-interprète à l'atelier", "15:45 — Choix et habillage", "16:45 — Promenade dans Higashiyama : ruelles pavées, vues sur la pagode, lumière des lanternes", "18:15 — Retour et changement de tenue", "18:30 — Fin de l'expérience"],
    goodToKnow: ["Le parcours est pavé et en pente douce ; des zori solides sont ajustées à votre pied.", "Les créneaux de l'heure dorée sont limités — réservez tôt pour l'automne et le printemps.", "Par temps de pluie, la promenade continue sous des parapluies traditionnels (très photogéniques).", "Un photographe professionnel peut être ajouté sur demande."],
    story: { heading: "Des rues faites pour la soie", body: "Les ruelles de Higashiyama ont été façonnées par les pèlerins, les maisons de thé et les ateliers pendant cinq siècles, et leur échelle convient toujours à une personne à pied en kimono. Les parcourir en soie à l'heure des lanternes n'est pas se déguiser ; c'est voir les rues comme elles ont été conçues pour être vues." },
  },
  {
    slug: "kyoto-sushi-class", city: "kyoto", category: "sushi",
    title: "Atelier de sushi à la kyotoïte et obanzai",
    tagline: "Saba-zushi pressé et cuisine familiale de Kyoto avec un chef chevronné",
    duration: "2 h 30", price: "¥35,000", group: "Privé · jusqu'à 6", ages: "Dès 8 ans", area: "Kyoto (centre-ville)",
    img: "/images/cat-sushi.jpg", alt: "Chef tranchant du poisson sur un comptoir en bois",
    gallery: [],
    whatYoullDo: [
      "Comprenez pourquoi Kyoto, sans accès à la mer, a bâti sa propre tradition de sushi autour du poisson salé.",
      "Pressez votre propre saba-zushi — sushi de maquereau — dans un moule en bois.",
      "Cuisinez deux ou trois obanzai, les plats d'accompagnement du quotidien à Kyoto, aux côtés du chef.",
      "Asseyez-vous ensemble pour manger ce que vous avez préparé, avec un thé de saison.",
    ],
    master: { quote: "Kyoto n'avait pas d'océan, alors nous avons inventé notre propre sushi. Je vais vous en apprendre le secret.", title: "Un chef chevronné de Kyoto", bio: "Il cuisine professionnellement la cuisine familiale de Kyoto depuis plus de trente ans et enseigne les techniques de sushi pressé que la ville a développées loin de la mer. L'adresse de sa cuisine est communiquée une fois votre réservation confirmée." },
    itinerary: ["10:30 — Rendez-vous avec votre guide-interprète à la cuisine", "10:45 — Introduction : le sushi de Kyoto, salé plutôt que cru", "11:00 — Pressage du saba-zushi ; cuisine des obanzai", "12:15 — Déjeuner ensemble au comptoir", "13:00 — Fin de l'expérience"],
    goodToKnow: ["Le maquereau salé est la pièce maîtresse ; alternatives disponibles en cas d'allergie.", "Entièrement pratique ; tabliers et tout le matériel fournis.", "Les recettes sont remises en anglais pour les emporter.", "Des ingrédients du marché signifient que les obanzai changent avec la saison."],
    story: { heading: "Le sushi, loin de la mer", body: "Avant le chemin de fer, le poisson de mer frais ne pouvait pas atteindre Kyoto — la ville a donc perfectionné la conservation. Le maquereau salé sur la côte voyageait par la « saba kaido », la route du maquereau, et était pressé sur du riz en saba-zushi. Le sushi de Kyoto est le goût de cette géographie, et on le prépare encore à la maison aujourd'hui." },
  },
];

export const toursFr: Tour[] = [
  {
    slug: "tokyo-private-day-tour", city: "tokyo", bookingType: "request",
    title: "Journée privée à Tokyo",
    tagline: "Huit heures avec un guide agréé, façonnées autour de vos centres d'intérêt",
    duration: "8 h", price: "¥60,000", group: "Groupe privé",
    img: "/images/tour-journey.jpg", alt: "Torii vermillon le long d'une allée du sanctuaire Fushimi Inari",
    description: "Une journée complète à Tokyo avec un guide privé agréé qui planifie pour éviter la foule — le bon quartier à la bonne heure, les repas réservés, les trajets réglés. Associez-la à une masterclass pour faire d'une journée une seule histoire plutôt qu'une liste.",
  },
  {
    slug: "kyoto-private-day-tour", city: "kyoto", bookingType: "request",
    title: "Journée privée à Kyoto",
    tagline: "Temples, thé et ruelles avec un guide agréé qui connaît les heures calmes",
    duration: "8 h", price: "¥60,000", group: "Groupe privé",
    img: "/images/tour-journey.jpg", alt: "Torii vermillon le long d'une allée du sanctuaire Fushimi Inari",
    description: "Une journée complète à Kyoto avec un guide privé agréé qui planifie autour de la foule — portes matinales, jardins tranquilles, les bonnes rues à la bonne heure. Associez-la à nos expériences de thé, de kimono ou de geiko pour composer une journée qui se lit comme une seule histoire.",
  },
];
