// French catalog. Slugs, prices and images mirror catalog.ts exactly —
// only human-readable text is localized. Vouvoiement throughout.

import type { Category, City, Experience, Tour } from "@/lib/catalog";

export const CANCELLATION_FR =
  "Annulation gratuite jusqu'à 7 jours avant l'expérience. Remboursement intégral si la séance est annulée par le lieu.";

export const citiesFr: City[] = [
  {
    slug: "tokyo", title: "Tokyo", jp: "東京", img: "/images/city-tokyo.jpg",
    lead: "Tokyo garde ses traditions derrière des portes discrètes, à quelques rues des néons. Nos masterclasses vous assoient auprès de ceux qui les font vivre — un chef sushi à son propre comptoir, des lutteurs à l'entraînement du matin, un forgeron de katana à sa forge — toujours avec un guide-interprète privé à vos côtés.",
  },
  {
    slug: "kyoto", title: "Kyoto", jp: "京都", img: "/images/city-kyoto.jpg",
    lead: "Kyoto est la ville où les rituels du Japon se vivent encore au quotidien. Nos expériences ouvrent des portes qui restent closes pour la plupart — une soirée avec une geiko, un bol de thé fouetté par une maîtresse, une promenade en soie dans Higashiyama — chacune avec un guide-interprète privé qui traduit chaque mot.",
  },
];

export const categoriesFr: Category[] = [
  { slug: "sushi", title: "Sushi", tag: "Gastronomie", mark: "寿", img: "/images/cat-sushi.jpg",
    lead: "Au Japon, le sushi est un métier qui se mesure en décennies, pas en recettes. Ces masterclasses en tout petit groupe vous placent derrière le comptoir avec des chefs en activité à Tokyo et Kyoto — façonner, assaisonner et goûter comme eux, avec un guide-interprète à vos côtés." },
  { slug: "sumo", title: "Sumo", tag: "Traditionnel", mark: "相", img: "/images/cat-sumo.jpg",
    lead: "Le sumo est le plus ancien sport vivant du Japon, et son quotidien est bien plus intime que le stade. Observez de près l'entraînement matinal d'une écurie en activité et comprenez la discipline derrière le cérémonial, votre guide expliquant chaque rituel à voix basse." },
  { slug: "tea-ceremony", title: "Cérémonie du thé", tag: "Traditionnel", mark: "茶", img: "/images/cat-tea.jpg",
    lead: "La cérémonie du thé condense l'hospitalité japonaise en un seul bol. Asseyez-vous face à une maîtresse de thé en activité, apprenez les gestes et partagez une heure sereine où chaque mouvement a un sens — traduit avec délicatesse, sans interruption." },
  { slug: "kimono", title: "Kimono", tag: "Traditionnel", mark: "着", img: "/images/cat-kimono.jpg",
    lead: "Un kimono est une architecture que l'on porte : soie, saison et maintien en harmonie. Laissez-vous habiller dans les règles par des stylistes professionnelles à Tokyo ou Kyoto, puis parcourez jardins et ruelles aux lanternes faites pour être vues de l'intérieur d'un kimono." },
  { slug: "geisha", title: "Geisha", tag: "Traditionnel", mark: "芸", img: "/images/cat-geisha.jpg",
    lead: "Une soirée avec une geiko est l'invitation la plus gardée de Kyoto. Conversation, danse et cuisine de saison dans un cadre privé, avec un interprète qui laisse l'échange couler naturellement dans votre langue." },
  { slug: "swordsmith", title: "Forgeron de sabres", tag: "Traditionnel", mark: "刀", img: "/images/cat-sword.jpg",
    lead: "Le sabre japonais, c'est mille ans de métallurgie dans une seule courbe. Visitez une forge en activité, regardez un forgeron agréé plier l'acier selon la tradition, et tenez l'histoire entre vos mains — guidé et traduit d'un bout à l'autre." },
  { slug: "anime-nail-art", title: "Nail art anime", tag: "Pop culture", mark: "爪", img: "/images/cat-nail.jpg",
    lead: "Les nail artists de Tokyo traitent l'ongle comme une toile. Apportez votre personnage ou motif préféré et repartez avec un fan art à porter, réalisé par une artiste qui fait cela tous les jours — la face légère et joueuse de l'artisanat japonais." },
];

export const experiencesFr: Experience[] = [
  {
    slug: "sushi-masterclass", city: "tokyo", category: "sushi",
    title: "Masterclass de sushi Edo-mae",
    tagline: "Façonnez des nigiri avec un chef de troisième génération, à son propre comptoir",
    duration: "2 h 30", price: "¥45,000", group: "Privé · jusqu'à 6", ages: "Dès 8 ans", area: "Tokyo (quartier de Tsukiji)",
    img: "/images/exp-sushi.jpg", alt: "Comptoir omakase en bois de hinoki, silencieux",
    gallery: [{ img: "/images/cat-sushi.jpg", alt: "Chef sushi tranchant du poisson sur une planche en bois" }],
    whatYoullDo: [
      "Prenez place au comptoir du chef, fermé au public pour votre séance.",
      "Apprenez à façonner le shari, assaisonner le neta et presser le nigiri, corrigé de sa main.",
      "Goûtez chaque pièce à l'instant où elle est faite, comme le sushi Edo-mae doit se manger.",
      "Terminez par la sélection du chef, servie à vous en tant que ses invités.",
    ],
    master: { quote: "Mon grand-père tenait mes mains au-dessus du riz. Aujourd'hui, je tiens les vôtres.", title: "Un chef sushi Edo-mae de troisième génération", bio: "Formé par son père et son grand-père au comptoir même où vous vous tiendrez, dans un quartier façonné par l'ancien marché de Tsukiji. Il prend rarement des élèves ; cette séance est l'exception. Le nom de son établissement est communiqué une fois votre réservation confirmée." },
    itinerary: ["10:00 — Rendez-vous avec votre guide-interprète près du lieu", "10:15 — Présentations, tablier, travail du couteau et shari", "11:15 — Façonnage des nigiri au comptoir", "12:00 — Dégustation et plat final du chef", "12:30 — Fin de l'expérience"],
    goodToKnow: ["Se déroule le matin avant l'ouverture ; les jours exacts dépendent de l'emploi du temps du chef.", "Le poisson cru est au cœur de la séance — signalez-nous vos allergies et nous adapterons.", "Séance pratique, debout la plupart du temps ; tabliers fournis.", "Photos bienvenues ; nous demandons de laisser la devanture et l'enseigne hors champ."],
    story: { heading: "L'histoire du sushi Edo-mae", body: "Edo-mae — « devant Edo » — désignait autrefois le poisson tiré de la baie de Tokyo, salé, pressé ou saisi pour tenir une journée sans glace. Les techniques ont survécu à la réfrigération parce qu'elles sont meilleures, pas parce qu'elles sont anciennes. Ce que vous apprenez à ce comptoir, c'est ce répertoire : vinaigre, sel, kombu et temps, appliqués pièce par pièce." },
  },
  {
    slug: "sumo-morning-practice", city: "tokyo", category: "sumo",
    title: "L'entraînement matinal de sumo, de l'intérieur",
    tagline: "Au bord du ring d'une écurie en activité, pendant que la journée d'entraînement se déroule",
    duration: "2 h", price: "¥38,000", group: "Petit groupe · jusqu'à 8", ages: "Dès 10 ans", area: "Tokyo (quartier de Ryogoku)",
    img: "/images/exp-sumo.jpg", alt: "Lutteurs de sumo à l'entraînement sur le ring d'une écurie de Tokyo",
    gallery: [{ img: "/images/cat-sumo.jpg", alt: "Lutteurs de sumo lors de la cérémonie d'entrée sur le ring" }],
    whatYoullDo: [
      "Entrez dans une écurie de sumo en activité avec votre guide, avant le réveil de la ville.",
      "Observez le keiko — l'entraînement du matin — depuis des places sur tatami, à quelques mètres du ring.",
      "Comprenez le sens de chaque exercice et de chaque rituel au moment où il se produit, dans votre langue.",
      "Rencontrez brièvement les lutteurs après l'entraînement, selon leur emploi du temps.",
    ],
    master: { quote: "L'entraînement n'est pas un spectacle. Mais ce matin, la porte vous est ouverte.", title: "Une écurie de sumo du quartier de Ryogoku", bio: "L'écurie forme des lutteurs classés depuis des décennies dans le quartier historique du sumo à Tokyo. Les visites sont limitées pour ne jamais perturber l'entraînement ; votre guide vous expliquera l'étiquette avant d'entrer. Le nom de l'écurie est communiqué une fois votre réservation confirmée." },
    itinerary: ["07:30 — Rendez-vous avec votre guide-interprète à Ryogoku", "07:45 — Rappel de l'étiquette, entrée dans l'écurie", "08:00 — Entraînement du matin, observé depuis les tatamis", "09:15 — Bref salut aux lutteurs (selon l'emploi du temps)", "09:30 — Fin de l'expérience"],
    goodToKnow: ["L'entraînement suit le calendrier des tournois ; certaines semaines sont indisponibles.", "Le silence est de rigueur pendant l'entraînement ; votre guide traduit à voix basse.", "Vous serez assis sur tatami jusqu'à 90 minutes ; coussins fournis.", "Tenue sobre ; pas de flash à l'intérieur de l'écurie."],
    story: { heading: "Le monde d'une écurie de sumo", body: "Le sumo professionnel se vit, il ne se joue pas. Les lutteurs partagent un toit, une cuisine et une hiérarchie stricte, et le ring du matin est l'endroit où tout cela devient visible — les jeunes balaient le dohyo, les anciens prennent les derniers combats, les plus durs. Voir le keiko, c'est voir toute la société du sport d'un coup." },
  },
  {
    slug: "kimono-photo-walk", city: "tokyo", category: "kimono",
    title: "Habillage en kimono et promenade photo dans un jardin",
    tagline: "Habillé(e) par une styliste professionnelle, puis une flânerie dans un jardin classique",
    duration: "3 h", price: "¥40,000", group: "Privé · jusqu'à 4", ages: "Tous âges", area: "Tokyo (quartier de jardins traditionnels)",
    img: "/images/exp-kimono.jpg", alt: "Femme en kimono rouge au bord d'un bassin à carpes dans un jardin japonais",
    gallery: [{ img: "/images/cat-kimono.jpg", alt: "Kimono ancien en soie à motif de faisan et de pivoine" }],
    whatYoullDo: [
      "Choisissez dans une garde-robe de kimonos en soie assortis à la saison.",
      "Faites-vous habiller dans les règles — chaque couche, pli et nœud — par une styliste professionnelle.",
      "Parcourez un jardin de promenade classique pendant que votre guide en raconte la conception et l'histoire.",
      "Prenez le temps de photographier aux meilleurs points de vue du jardin.",
    ],
    master: { quote: "Un kimono ne se porte pas — il se construit. Et je vais le construire sur vous.", title: "Une styliste de kimono professionnelle", bio: "Elle habille des clientes pour des mariages, des cérémonies et le cinéma depuis plus de vingt ans, et compose chaque ensemble selon la personne et la saison plutôt que de le tirer d'un portant de costumes. L'adresse de son atelier est communiquée une fois votre réservation confirmée." },
    itinerary: ["10:00 — Rendez-vous avec votre guide-interprète à l'atelier", "10:15 — Choix du kimono et habillage", "11:15 — Promenade dans le jardin et photos", "12:45 — Retour, changement de tenue, thé", "13:00 — Fin de l'expérience"],
    goodToKnow: ["Kimonos disponibles dans une large gamme de tailles ; indiquez-nous votre taille à l'avance.", "Marcher confortablement fait partie de l'expérience ; chaussettes tabi fournies.", "Par temps de pluie, la promenade passe par les allées couvertes et le pavillon de thé du jardin.", "Un photographe professionnel peut être ajouté sur demande."],
    story: { heading: "Pourquoi l'habillage compte", body: "Un kimono ne s'enfile pas ; il se construit — couche sur couche, ajusté au corps jusqu'à ce que la silhouette soit juste. Bien porté, il change la façon dont on se tient et marche, et c'est exactement pour cela que le jardin vient après le vestiaire. Le jardin a été conçu pour des gens qui avancent au rythme d'un kimono." },
  },
  {
    slug: "katana-forge-visit", city: "tokyo", category: "swordsmith",
    title: "Katana : visite de la forge d'un maître forgeron",
    tagline: "Regardez un forgeron agréé plier l'acier selon la tradition",
    duration: "3 h", price: "¥90,000", group: "Privé · jusqu'à 4", ages: "Dès 12 ans", area: "Grand Tokyo (quartier d'ateliers)",
    img: "/images/cat-sword.jpg", alt: "Lame de katana polie, photographiée sur fond noir",
    gallery: [],
    whatYoullDo: [
      "Rendez-vous avec votre guide dans une forge en activité rarement ouverte aux visiteurs.",
      "Regardez l'acier tamahagane chauffé, martelé et plié sur l'enclume.",
      "Tenez des lames finies et apprenez comment le polisseur révèle le hamon.",
      "Posez toutes vos questions au forgeron — votre guide traduit l'échange entier.",
    ],
    master: { quote: "L'acier se souvient de chaque coup. Venez le regarder se souvenir.", title: "Un forgeron de sabres japonais agréé", bio: "L'un des rares forgerons autorisés à forger des nihonto aujourd'hui, il travaille dans la forge au charbon traditionnelle avec un seul apprenti. Les jours de forge sont irréguliers ; les dates sont confirmées individuellement. L'adresse de sa forge est communiquée une fois votre réservation confirmée." },
    itinerary: ["09:30 — Rendez-vous avec votre guide-interprète ; trajet ensemble jusqu'à la forge", "10:30 — Présentation de la forge et de ses outils", "11:00 — Démonstration de forge sur l'enclume", "12:00 — Manipulation des lames, questions au forgeron", "12:30 — Fin de l'expérience (retour avec votre guide)"],
    goodToKnow: ["La forge est chaude et bruyante pendant les démonstrations ; protections auditives fournies.", "Chaussures fermées et vêtements en fibres naturelles obligatoires près du feu.", "Les dates dépendent du calendrier de production du forgeron — réservez tôt.", "Les lames ne se manipulent que sous la supervision directe du forgeron."],
    story: { heading: "Mille ans dans une seule courbe", body: "Le sabre japonais survit parce que sa fabrication n'a jamais été simplifiée. Le même acier est encore fondu à partir de sable ferrugineux, plié pour chasser les impuretés, et trempé dans l'eau pour créer la courbe et le hamon en un seul instant de risque. Chaque forgeron agréé en activité aujourd'hui est une ligne directe vers cette méthode ininterrompue." },
  },
  {
    slug: "anime-nail-art-session", city: "tokyo", category: "anime-nail-art",
    title: "Séance de nail art anime",
    tagline: "Votre personnage préféré, peint par une nail artist de Tokyo",
    duration: "2 h", price: "¥18,000", group: "Privé · jusqu'à 2", ages: "Tous âges", area: "Tokyo (Akihabara / Harajuku)",
    img: "/images/cat-nail.jpg", alt: "Rue d'Akihabara sous les néons, la nuit",
    gallery: [],
    whatYoullDo: [
      "Partagez à l'avance vos personnages ou visuels préférés avec l'artiste.",
      "Regardez de minuscules illustrations peintes à la main prendre forme, ongle après ongle.",
      "Discutez avec l'artiste de la culture du nail art et du fan art à Tokyo pendant qu'elle travaille.",
      "Repartez avec un gel art durable — et les conseils d'entretien de l'artiste.",
    ],
    master: { quote: "Apportez-moi votre personnage préféré. Je le ferai tenir sur huit millimètres.", title: "Une nail artist de Tokyo spécialisée dans les personnages", bio: "Son carnet est rempli de fans qui prennent l'avion pour son travail de personnages peints à la main, des franchises classiques aux sorties de la saison. Elle peint à main levée avec des pinceaux plus fins qu'une mine de crayon. L'adresse de son salon est communiquée une fois votre réservation confirmée." },
    itinerary: ["14:00 — Rendez-vous avec votre guide-interprète au salon", "14:10 — Consultation autour de vos références", "14:30 — Séance de peinture", "15:50 — Couche de finition et entretien", "16:00 — Fin de l'expérience"],
    goodToKnow: ["Envoyez des images de référence à la réservation pour que l'artiste prépare les couleurs.", "Le gel art tient en général trois à quatre semaines avec un usage normal.", "Les motifs complexes peuvent prolonger la séance ; la durée est confirmée à l'avance.", "Cette expérience est dans une gamme de prix plus légère que nos masterclasses — elle n'en est pas moins artisanale."],
    story: { heading: "Un fan art à porter", body: "Le nail art a grandi aux côtés de la culture des personnages au Japon, et à Tokyo les deux ont fusionné en un genre à part : la micro-illustration, peinte sur une toile mobile plus petite qu'un timbre. Les meilleures artistes sont réservées des semaines à l'avance par les habitants. Cette séance vous ouvre l'un de ces fauteuils." },
  },
  {
    slug: "evening-with-geiko", city: "kyoto", category: "geisha", bookingType: "request", status: "live",
    title: "Banquet ozashiki avec maiko et geiko",
    tagline: "Un salon de banquet privé à Kyoto — dîner, danse et jeux de salon avec geiko et maiko",
    duration: "2 h", price: "¥139,600", priceUnit: "group", group: "Privé · 2 à 40 convives", ages: "Tous âges", area: "Kyoto (Gion / Higashiyama)",
    img: "/images/exp-geisha.jpg", alt: "Maiko exécutant une danse traditionnelle avec un éventail",
    gallery: [{ img: "/images/cat-geisha.jpg", alt: "Maiko en tenue complète dans un quartier de maisons de thé de Kyoto" }],
    cancellation: "Des frais d'annulation s'appliquent dès que votre réservation est confirmée : 50 % jusqu'à 4 jours avant, 75 % de 3 à 2 jours avant, 100 % à partir de la veille (heure du Japon ; non-présentation 100 %). Les changements de date suivent le même barème, et la réduction du nombre de convives applique les frais aux places libérées. Si aucune geiko ou maiko ne peut être réservée pour votre date, vous êtes intégralement remboursé.",
    whatYoullDo: [
      "Installez-vous dans votre propre salon de banquet — jamais partagé avec d'autres convives.",
      "Dînez d'une cuisine de Kyoto de saison pendant que geiko et maiko rejoignent votre table pour converser.",
      "Assistez à une danse exécutée à portée de main, puis essayez ensemble les jeux de salon ozashiki.",
      "Terminez par des photos souvenir avec vos hôtesses.",
    ],
    master: { quote: "Pour un soir, cette pièce est la vôtre. Venez, parlons.", title: "Geiko et maiko des hanamachi de Kyoto", bio: "Votre soirée est animée par des geiko ou maiko en activité du monde des fleurs et des saules de Kyoto, engagées spécialement pour votre date. Le lieu est une maison de banquet privée du quartier de Gion / Higashiyama ; son nom et son adresse sont communiqués une fois votre réservation confirmée." },
    itinerary: ["10 min avant — Arrivée au lieu avec votre guide (adresse dans votre confirmation)", "0:00 — Bienvenue dans votre salon privé ; le banquet commence", "0:30 — Geiko et maiko rejoignent votre table ; conversation pendant le dîner", "1:15 — Danse et jeux de salon ozashiki", "1:50 — Photos souvenir", "2:00 — Fin de la soirée"],
    goodToKnow: [
      "Tous les jours sauf pendant les fêtes du Nouvel An, débuts de 12:00 à 20:30 — réservez au moins 3 jours à l'avance (clôture à 17 h, heure du Japon).",
      "Tarif par groupe, tout compris : ¥139,600 pour 2 convives, ¥157,500 pour 3, ¥166,000 pour 4, ¥190,000 pour 5 ; groupes plus grands (jusqu'à 40) sur demande.",
      "Tarifs haute saison du 15 mars au 31 mai et du 1er octobre au 30 novembre (à partir de ¥159,600 pour 2 convives).",
      "Enfants : gratuit sans repas jusqu'à 2 ans, demi-tarif adulte de 3 à 11 ans, tarif adulte avec menu complet dès 12 ans.",
      "Allergies et régimes particuliers pris en compte — signalez-les à la réservation.",
      "Envie d'une salle plus animée ? Une geiko ou maiko supplémentaire peut être engagée pour ¥60,500.",
    ],
    story: { heading: "Le monde du karyukai", body: "Le « monde des fleurs et des saules » de Kyoto repose depuis trois siècles sur la recommandation et la confiance. Une geiko n'est pas une artiste à louer mais une artiste dont les soirées se prolongent par les relations entre maisons de thé et clients fidèles. Être assis dans cette pièce, avec une conversation qui coule dans votre propre langue, est l'accès le plus rare que Kyoto puisse offrir." },
    availabilityNote: "Fermé pendant les fêtes du Nouvel An.",
    galleryNote: "La salle et les plats photographiés sont donnés à titre d'exemple ; ils varient selon la date et la saison.",
    highlights: [
      { icon: "group", title: "La salle est à vous", body: "Un salon de banquet privé réservé à votre groupe, jamais partagé avec d'autres convives." },
      { icon: "chat", title: "Une conversation, pas seulement un spectacle", body: "Geiko et maiko s'installent à votre table pour discuter, dansent à portée de main, puis jouent avec vous aux jeux d'ozashiki." },
      { icon: "interpreter", title: "Posez toutes vos questions", body: "Un guide-interprète porte la conversation dans les deux sens : vos questions atteignent la salle et les réponses vous reviennent." },
    ],
    included: [
      "Un salon de banquet privé pour votre groupe",
      "Une cuisine de Kyoto de saison",
      "Une geiko ou une maiko à votre table : conversation, une danse et des jeux d'ozashiki",
      "Des photos souvenir avec vos hôtesses",
      "Un guide-interprète à vos côtés du début à la fin",
    ],
    notIncluded: [
      "Une geiko ou maiko supplémentaire, 60 500 ¥",
      "Les groupes de six personnes et plus font l'objet d'un devis",
    ],
    schedule: [
      { time: "10 min avant", title: "Arrivée avec votre guide", body: "L'adresse figure dans votre confirmation. Votre guide vous attend à proximité et vous accompagne à l'intérieur." },
      { time: "0:00", title: "Votre salle privée", body: "Vous prenez place ; le banquet commence." },
      { time: "0:30", title: "Geiko et maiko vous rejoignent", body: "Conversation autour du dîner, l'interprète assurant les deux sens." },
      { time: "1:15", title: "Danse et jeux d'ozashiki", body: "Une danse assez proche pour entendre la soie bouger, puis des jeux de salon simples et disputés." },
      { time: "1:50", title: "Photographies", body: "Photos souvenir avec vos hôtesses." },
      { time: "2:00", title: "Fin de la soirée" },
    ],
    venue: {
      known: ["Quartier de Gion / Higashiyama, Kyoto", "Une maison de banquet privée ; la salle est à vous pour la soirée", "Rendez-vous sur place : aucun transfert n'est organisé"],
      afterBooking: ["Le nom et l'adresse de la maison", "Un plan et l'itinéraire à pied depuis la gare la plus proche", "Le contact de votre guide pour la soirée"],
      img: "/images/city-kyoto.jpg", alt: "Ruelle bordée de lanternes à Higashiyama, Kyoto",
    },
    faq: [
      { q: "Sera-ce une geiko ou une maiko ?", a: "Une geiko ou une maiko est réservée pour votre date. Laquelle dépend des disponibilités du soir ; si vous avez une préférence, indiquez-la lors de votre demande et nous la transmettrons, sans pouvoir la garantir." },
      { q: "Peut-on ajouter une seconde artiste ?", a: "Oui : une geiko ou maiko supplémentaire peut être réservée pour 60 500 ¥, ce qui anime nettement la soirée. Demandez-le lors de votre demande de date." },
      { q: "Peut-on prendre des photos ?", a: "Oui. Un moment est réservé en fin de soirée aux photos souvenir avec vos hôtesses. Votre guide vous indiquera si, pendant la danse, il convient de poser les appareils." },
      { q: "Les régimes et allergies sont-ils pris en compte ?", a: "Oui. Précisez-les lors de votre demande (allergies, végétarien, végan, halal) : la réponse de la cuisine vous parvient avec la confirmation, avant tout paiement." },
      { q: "Les enfants sont-ils les bienvenus ?", a: "Oui. Les moins de 2 ans participent gratuitement sans repas, les 3–11 ans paient la moitié du tarif adulte, et à partir de 12 ans le tarif adulte avec le menu complet. On s'assied sur tatami ; dites-nous si quelqu'un a besoin d'une chaise." },
      { q: "Combien de temps à l'avance faut-il réserver ?", a: "Au moins trois jours avant, avant 17 h heure du Japon. Le printemps et l'automne se remplissent en premier : pour ces périodes, demandez votre date dès que vos vols sont confirmés." },
    ],
  },
  {
    slug: "tea-ceremony-with-master", city: "kyoto", category: "tea-ceremony",
    title: "Cérémonie du thé avec une maîtresse de thé",
    tagline: "Une heure paisible de temae dans une maison de thé de Kyoto, bol après bol",
    duration: "1 h 30", price: "¥30,000", group: "Privé · jusqu'à 6", ages: "Tous âges", area: "Kyoto (quartier des temples)",
    img: "/images/craft-hands.jpg", alt: "Hôtesse de cérémonie du thé posant un bol sur le tatami devant des invités assis",
    gallery: [{ img: "/images/cat-tea.jpg", alt: "Hôtesse préparant le matcha lors d'une réunion de thé en plein air" }],
    whatYoullDo: [
      "Entrez dans une maison de thé en activité par son allée de jardin, comme les invités depuis des siècles.",
      "Assistez à un temae complet — la chorégraphie du charbon, de l'eau, du fouet et du bol.",
      "Fouettez votre propre bol de matcha sous la direction de la maîtresse.",
      "Apprenez comment les ustensiles, le rouleau et les fleurs sont choisis pour ce jour et cette saison.",
    ],
    master: { quote: "Une fois, une rencontre. Ce bol de thé ne se reproduira jamais.", title: "Une maîtresse de thé de Kyoto en activité", bio: "Diplômée de l'une des grandes écoles de thé, elle pratique depuis plus de trente ans et reçoit tout au long de l'année. Sa maison de thé se trouve près de l'un des quartiers de temples de Kyoto ; l'adresse exacte est communiquée une fois votre réservation confirmée." },
    itinerary: ["10:00 — Rendez-vous avec votre guide-interprète près de la maison de thé", "10:10 — Allée du jardin, purification et entrée dans la pièce", "10:20 — Temae de la maîtresse, premiers bols et douceurs", "10:50 — Fouettez votre propre bol ; examen des ustensiles et conversation", "11:30 — Fin de l'expérience"],
    goodToKnow: ["Assis sur tatami ; on peut étendre les jambes et des tabourets bas sont disponibles.", "Les chaussettes blanches sont appréciées ; nous vous le rappellerons la veille.", "Les douceurs ne contiennent aucun produit animal ; autres besoins pris en compte sur demande.", "Mouvements et photos s'interrompent pendant le temae lui-même — votre guide vous fera signe."],
    story: { heading: "Une fois, une rencontre", body: "Ichigo ichie — l'idée que cette réunion, avec ces personnes, n'a lieu qu'une seule fois — est le cœur de la cérémonie du thé. Tout dans la pièce répond au jour : le rouleau, la fleur, la glaçure du bol face à la saison. Le rituel n'est pas un spectacle mais une attention, offerte aux invités un bol à la fois." },
  },
  {
    slug: "kimono-higashiyama-walk", city: "kyoto", category: "kimono",
    title: "Kimono et promenade aux lanternes dans Higashiyama",
    tagline: "Vêtu(e) de soie, puis dans les ruelles les plus chargées d'histoire de Kyoto à l'heure dorée",
    duration: "3 h", price: "¥40,000", group: "Privé · jusqu'à 4", ages: "Tous âges", area: "Kyoto (Higashiyama)",
    img: "/images/cat-kimono.jpg", alt: "Kimono ancien en soie à motif de faisan et de pivoine",
    gallery: [{ img: "/images/city-kyoto.jpg", alt: "Rue Yasaka-dori bordée de lanternes à l'aube, avec la pagode de Yasaka" }],
    whatYoullDo: [
      "Faites-vous habiller de soie de saison par une professionnelle du kitsuke de Kyoto.",
      "Parcourez les ruelles pavées de Higashiyama au moment où les lanternes s'allument.",
      "Écoutez l'histoire des rues de la pagode racontée par votre guide, chemin faisant.",
      "Faites une pause photo là où la foule s'éclaircit et où la lumière est la plus belle.",
    ],
    master: { quote: "Marchez dans ces ruelles en soie à l'heure des lanternes — vous verrez pourquoi nous nous habillons encore ainsi.", title: "Une professionnelle du kitsuke (habillage en kimono) de Kyoto", bio: "Formée à l'habillage de cérémonie pour les saisons de fêtes de Kyoto, elle choisit dans une garde-robe de soies anciennes et contemporaines plutôt que dans du polyester de location. Son atelier de Higashiyama est à quelques pas du parcours ; l'adresse est communiquée une fois votre réservation confirmée." },
    itinerary: ["15:30 — Rendez-vous avec votre guide-interprète à l'atelier", "15:45 — Choix et habillage", "16:45 — Promenade dans Higashiyama : ruelles pavées, vues sur la pagode, lumière des lanternes", "18:15 — Retour et changement de tenue", "18:30 — Fin de l'expérience"],
    goodToKnow: ["Le parcours est pavé et en pente douce ; des zori solides sont ajustées à votre pied.", "Les créneaux de l'heure dorée sont limités — réservez tôt pour l'automne et le printemps.", "Par temps de pluie, la promenade continue sous des parapluies traditionnels (très photogéniques).", "Un photographe professionnel peut être ajouté sur demande."],
    story: { heading: "Des rues faites pour la soie", body: "Les ruelles de Higashiyama ont été façonnées par les pèlerins, les maisons de thé et les ateliers pendant cinq siècles, et leur échelle convient toujours à une personne à pied en kimono. Les parcourir en soie à l'heure des lanternes n'est pas se déguiser ; c'est voir les rues comme elles ont été conçues pour être vues." },
  },
  {
    slug: "kyoto-sushi-class", city: "kyoto", category: "sushi",
    title: "Atelier de sushi à la kyotoïte et obanzai",
    tagline: "Saba-zushi pressé et cuisine familiale de Kyoto avec un chef chevronné",
    duration: "2 h 30", price: "¥35,000", group: "Privé · jusqu'à 6", ages: "Dès 8 ans", area: "Kyoto (centre-ville)",
    img: "/images/cat-sushi.jpg", alt: "Chef tranchant du poisson sur un comptoir en bois",
    gallery: [],
    whatYoullDo: [
      "Comprenez pourquoi Kyoto, sans accès à la mer, a bâti sa propre tradition de sushi autour du poisson salé.",
      "Pressez votre propre saba-zushi — sushi de maquereau — dans un moule en bois.",
      "Cuisinez deux ou trois obanzai, les plats d'accompagnement du quotidien à Kyoto, aux côtés du chef.",
      "Asseyez-vous ensemble pour manger ce que vous avez préparé, avec un thé de saison.",
    ],
    master: { quote: "Kyoto n'avait pas d'océan, alors nous avons inventé notre propre sushi. Je vais vous en apprendre le secret.", title: "Un chef chevronné de Kyoto", bio: "Il cuisine professionnellement la cuisine familiale de Kyoto depuis plus de trente ans et enseigne les techniques de sushi pressé que la ville a développées loin de la mer. L'adresse de sa cuisine est communiquée une fois votre réservation confirmée." },
    itinerary: ["10:30 — Rendez-vous avec votre guide-interprète à la cuisine", "10:45 — Introduction : le sushi de Kyoto, salé plutôt que cru", "11:00 — Pressage du saba-zushi ; cuisine des obanzai", "12:15 — Déjeuner ensemble au comptoir", "13:00 — Fin de l'expérience"],
    goodToKnow: ["Le maquereau salé est la pièce maîtresse ; alternatives disponibles en cas d'allergie.", "Entièrement pratique ; tabliers et tout le matériel fournis.", "Les recettes sont remises en anglais pour les emporter.", "Des ingrédients du marché signifient que les obanzai changent avec la saison."],
    story: { heading: "Le sushi, loin de la mer", body: "Avant le chemin de fer, le poisson de mer frais ne pouvait pas atteindre Kyoto — la ville a donc perfectionné la conservation. Le maquereau salé sur la côte voyageait par la « saba kaido », la route du maquereau, et était pressé sur du riz en saba-zushi. Le sushi de Kyoto est le goût de cette géographie, et on le prépare encore à la maison aujourd'hui." },
  },
];

export const toursFr: Tour[] = [
  {
    slug: "tokyo-private-day-tour", city: "tokyo", bookingType: "request",
    title: "Journée privée à Tokyo",
    tagline: "Huit heures avec un guide agréé, façonnées autour de vos centres d'intérêt",
    duration: "8 h", price: "¥60,000", group: "Groupe privé",
    img: "/images/tour-journey.jpg", alt: "Torii vermillon le long d'une allée du sanctuaire Fushimi Inari",
    description: "Une journée complète à Tokyo avec un guide privé agréé qui planifie pour éviter la foule — le bon quartier à la bonne heure, les repas réservés, les trajets réglés. Associez-la à une masterclass pour faire d'une journée une seule histoire plutôt qu'une liste.",
  },
  {
    slug: "kyoto-private-day-tour", city: "kyoto", bookingType: "request",
    title: "Journée privée à Kyoto",
    tagline: "Temples, thé et ruelles avec un guide agréé qui connaît les heures calmes",
    duration: "8 h", price: "¥60,000", group: "Groupe privé",
    img: "/images/tour-journey.jpg", alt: "Torii vermillon le long d'une allée du sanctuaire Fushimi Inari",
    description: "Une journée complète à Kyoto avec un guide privé agréé qui planifie autour de la foule — portes matinales, jardins tranquilles, les bonnes rues à la bonne heure. Associez-la à nos expériences de thé, de kimono ou de geiko pour composer une journée qui se lit comme une seule histoire.",
  },
];
