// Spanish catalog. Slugs, prices and images mirror catalog.ts exactly —
// only human-readable text is localized. First-pass translation; have a
// native speaker review before heavy ad spend.

import type { Category, City, Experience, Tour } from "@/lib/catalog";

export const CANCELLATION_ES =
  "Cancelación gratuita hasta 7 días antes de la experiencia. Reembolso completo si el anfitrión cancela la sesión.";

export const citiesEs: City[] = [
  {
    slug: "tokyo", title: "Tokio", jp: "東京", img: "/images/city-tokyo.jpg",
    lead: "Tokio guarda sus tradiciones a pocas calles del neón. Empezamos con una clase privada de caligrafía con pincel en Shinjuku: kanji elegidos por el significado de tu nombre, enseñados en inglés por una profesora de caligrafía. Desde Tokio también puedes pasar un día de golf cerca del monte Fuji, con coche privado desde tu hotel. Pronto habrá más experiencias en Tokio.",
  },
  {
    slug: "kyoto", title: "Kioto", jp: "京都", img: "/images/city-kyoto.jpg",
    lead: "Descubre otra cara de Kioto a través de sus tradiciones vivas. Pasa una velada privada con una geiko o maiko — cena, danza y conversación en tu propia sala — y pronto más experiencias en Kioto de comida, oficio y accesos especiales.",
  },
];

export const categoriesEs: Category[] = [
  { slug: "sushi", title: "Sushi", tag: "Gastronomía", mark: "寿", img: "/images/cat-sushi.jpg",
    lead: "En Japón, el sushi es un oficio que se mide en décadas, no en recetas. Estas clases magistrales en grupos reducidos te ponen detrás de la barra con chefs en activo de Tokio y Kioto — moldeando, sazonando y probando como ellos, con un guía intérprete a tu lado." },
  { slug: "sumo", title: "Sumo", tag: "Tradicional", mark: "相", img: "/images/cat-sumo.jpg",
    lead: "El sumo es el deporte vivo más antiguo de Japón, y su día a día es mucho más íntimo que el estadio. Observa de cerca el entrenamiento matinal en una cuadra en activo y entiende la disciplina detrás de la ceremonia, con tu guía explicando cada ritual en voz baja." },
  { slug: "tea-ceremony", title: "Ceremonia del té", tag: "Tradicional", mark: "茶", img: "/images/cat-tea.jpg",
    lead: "La ceremonia del té destila la hospitalidad japonesa en un solo cuenco. Siéntate con una maestra de té en activo, aprende los gestos y comparte una hora serena donde cada movimiento tiene sentido — traducido con delicadeza, sin interrupciones." },
  { slug: "kimono", title: "Kimono", tag: "Tradicional", mark: "着", img: "/images/cat-kimono.jpg",
    lead: "Un kimono es arquitectura vestida: seda, estación y postura en armonía. Déjate vestir como es debido por estilistas profesionales en Tokio o Kioto, y pasea por jardines y callejones de farolillos hechos para verse desde dentro de uno." },
  { slug: "geisha", title: "Geisha", tag: "Tradicional", mark: "芸", img: "/images/geiko-dance.jpg",
    lead: "Una velada con una geiko es la invitación más celosamente guardada de Kioto. Comparte conversación, danza y cocina de temporada en un entorno privado, con un intérprete que deja fluir el intercambio en tu idioma." },
  { slug: "swordsmith", title: "Forja de katanas", tag: "Tradicional", mark: "刀", img: "/images/cat-sword.jpg",
    lead: "La espada japonesa son mil años de metalurgia en una sola curva. Visita una fragua en activo, observa a un forjador titulado plegar el acero al modo tradicional y sostén la historia en tus manos — con guía y traducción en todo momento." },
  { slug: "anime-nail-art", title: "Nail art de anime", tag: "Cultura pop", mark: "爪", img: "/images/cat-nail.jpg",
    lead: "Las artistas de uñas de Tokio tratan cada uña como un lienzo. Trae a tu personaje favorito y llévate arte fan portátil pintado por una artista que vive de esto — el lado más ligero y juguetón del oficio japonés." },
  { slug: "calligraphy", title: "Caligrafía", tag: "Arte y artesanía", mark: "書", img: "/images/kanji-works-table.jpg",
    lead: "Un pincel, tinta negra y un solo carácter. Aprende los trazos con una profesora, elige kanji con el significado de tu nombre y llévate una obra hecha por ti." },
  { slug: "golf", title: "Golf", tag: "Deporte", mark: "球", img: "/images/golf-flag-fuji.jpg",
    lead: "El golf en Japón tiene sus propias costumbres y algunas de las mejores vistas del país. Un día de golf privado en la región del monte Fuji, con tu campo y tu hora de salida organizados para ti, coche privado desde tu hotel de Tokio y apoyo en inglés." },
];

export const experiencesEs: Experience[] = [
  {
    slug: "kanji-name-calligraphy", city: "tokyo", category: "calligraphy",
    title: "Tu nombre en kanji: clase de caligrafía con pincel en Tokio",
    tagline: "Crea una obra de arte única con un kanji inspirado en tu propio nombre, en una clase privada en Tokio. Antes del día te preguntamos por tu nombre y su significado, y la profesora prepara tres kanji para ti; eliges el que más te represente y lo conviertes en arte con pincel y tinta.",
    overview: ["No es una clase de caligrafía para escribir a la perfección ni para seguir reglas estrictas. Lo importante es lo que tu kanji significa para ti y expresarlo a tu manera.", "Primero descubres cómo se mueve el pincel: trazos, texturas de pincel seco, los matices de la tinta. Después eliges un estilo —Cute, Bold o Elegant— y desarrollas tu carácter con la guía personalizada de la profesora. No hace falta experiencia con el pincel ni con los kanji.", "Un sello rojo completa la obra, y te la llevas: un kanji elegido para ti y creado con tus propias manos, una pieza de arte de tu paso por Tokio y no un simple recuerdo."],
    overviewFigure: { img: "/images/kanji-styles.jpg", alt: "Ejemplos de estilo: seis kanji en los estilos Cute, Bold y Elegant", caption: "Los tres estilos para elegir: Cute, Bold y Elegant (ejemplos)." },
    duration: "Unas 2 horas", price: "¥19,800", group: "Privado · 1–4 personas", ages: "Desde 10 años", area: "Tokio (Shinjuku)",
    img: "/images/kanji-hero-results.jpg", alt: "Dos participantes sonrientes con los kanji que pintaron en una clase de caligrafía en Tokio",
    gallery: [
      { img: "/images/kanji-teacher-demo.jpg", alt: "La profesora muestra un trazo mientras un participante practica a su lado" },
      { img: "/images/kanji-guests-works.jpg", alt: "Dos participantes con sus kanji terminados: 灯 (luz) y 夢 (sueño)" },
      { img: "/images/kanji-finished-stand.jpg", alt: "Un 夢 (sueño) terminado sobre su soporte de madera, listo para llevar" },
      { img: "/images/kanji-works-table.jpg", alt: "Obras terminadas secándose, cada una con su sello rojo" },
      { img: "/images/kanji-brush-focus.jpg", alt: "Un participante concentrado en su obra final" },
      { img: "/images/kanji-teacher-yume.jpg", alt: "La profesora con 夢 (sueño) en un estilo desenfadado" },
      { img: "/images/kanji-writing-together.jpg", alt: "Dos participantes practicando en la mesa compartida" },
      { img: "/images/kanji-teacher-guides.jpg", alt: "La profesora guía la práctica de una participante" },
      { img: "/images/kanji-teacher-shows.jpg", alt: "La profesora muestra un carácter terminado" },
      { img: "/images/kanji-brush-closeup.jpg", alt: "Primer plano de un pincel sobre papel de práctica" },
      { img: "/images/kanji-teacher-check.jpg", alt: "La profesora revisa las hojas de práctica" },
      { img: "/images/kanji-table-setup.jpg", alt: "Pincel, tinta y tintero junto a un 舞 (danza) terminado" },
      { img: "/images/kanji-teacher-seal.jpg", alt: "La profesora con una obra terminada y la caja de sellos rojos" },
      { img: "/images/kanji-studio.jpg", alt: "El estudio luminoso con una mesa larga compartida" },
    ],
    langTag: "Clase en inglés",
    includedShort: "Clase con la profesora · Todo el material · Tu obra + soporte",
    cancellation: "Los días se cuentan hasta la fecha de la clase, en hora de Japón. Los cambios de fecha siguen la misma escala, si otra fecha tiene plazas. El estudio se alquila por horas: si llegas tarde, la práctica se acorta en lugar de alargar la clase. Si la profesora tiene que cancelar, te avisamos antes de las 17:00 del día anterior y te devolvemos todo.",
    highlights: [
      { icon: "chat", title: "Tres kanji preparados para ti", body: "Antes de la clase te preguntamos por tu nombre y su significado. La profesora prepara tres caracteres para ti; el día de la clase eliges el que más te represente." },
      { icon: "brush", title: "Arte, no un examen de caligrafía", body: "Elige un estilo —Cute, Bold o Elegant— y haz tuyo el carácter. No hace falta experiencia con el pincel ni con los kanji." },
      { icon: "photo", title: "Una obra para llevarte", body: "Tu obra final sobre un shikishi, con sello rojo y en un soporte de madera, hecha y entregada el mismo día." },
      { icon: "group", title: "Solo tu grupo", body: "Las clases no se comparten con otros clientes: de una a cuatro personas, una profesora, una mesa larga." },
    ],
    included: ["Una clase de dos horas guiada por la profesora en inglés sencillo", "Todo el material: pincel, tinta, tintero de piedra, fieltro y papel de práctica, y un delantal", "Tu obra final sobre un shikishi, con soporte de madera para exponerla", "El sello rojo en tu obra y tiempo para fotos al final", "Impuestos incluidos: no se añade nada el día de la clase"],
    notIncluded: ["Transporte al estudio (encuentro en el lugar)", "Postales y láminas de la profesora, a la venta en el estudio si quieres alguna"],
    teacher: {
      img: "/images/kanji-teacher-portrait.jpg", alt: "Tu profesora con un carácter que pintó ella misma",
      credentials: ["7 años enseñando arte de caligrafía japonesa con pincel", "Más de 25 años creando arte: pastel, acuarela y otras técnicas artísticas y artesanales"],
      comment: "El pincel, la tinta y los kanji tienen una belleza y una profundidad propias, arraigadas en la cultura japonesa. Con esta experiencia espero que disfrutes descubriendo la cultura japonesa mientras te expresas libremente, poniendo tu nombre, tus sentimientos o un significado personal en un solo kanji. Aunque sea tu primera vez, te guiaré con cuidado y de forma personalizada para que todos puedan disfrutar con confianza.",
    },
    schedule: [
      { time: "10:30", title: "Bienvenida", body: "En qué consiste la clase y presentación del pincel, la tinta y el papel." },
      { time: "10:50", title: "Práctica con el pincel y elección de tu kanji", body: "Familiarízate con el pincel —trazos, texturas de pincel seco, los matices de la tinta— y descubre el significado de tus tres kanji; elige el que sientas tuyo.", img: "/images/kanji-brush-closeup.jpg" },
      { time: "11:10", title: "Tu estilo: Cute, Bold o Elegant", body: "Elige la dirección que te guste y practícala con la guía personalizada de la profesora.", img: "/images/kanji-teacher-demo.jpg" },
      { time: "11:40", title: "Tu obra final", body: "Un ensayo a tamaño real y luego la versión final sobre un shikishi.", img: "/images/kanji-brush-focus.jpg" },
      { time: "12:00", title: "Sello, compartir y fotos", body: "Se estampa el sello rojo; os enseñáis las obras y hacéis fotos.", img: "/images/kanji-guests-works.jpg" },
      { time: "12:15", title: "Tiempo libre", body: "Más práctica o una charla con la profesora antes de irte.", img: "/images/kanji-teacher-yume.jpg" },
      { time: "12:30", title: "Fin de la clase" },
    ],
    venue: {
      known: ["Un estudio de alquiler en Shinjuku, Tokio; la dirección exacta llega con la confirmación", "Mesas y sillas; una sala luminosa con una mesa larga compartida", "Encuentro con la profesora en el estudio 5 minutos antes del inicio", "La tinta mancha: ven con ropa que no te importe ensuciar (hay delantales)"],
      afterBooking: ["El nombre y la dirección del estudio", "Indicaciones desde la estación más cercana", "El contacto de la profesora para ese día"],
      img: "/images/kanji-studio.jpg", alt: "El estudio con su mesa larga compartida",
    },
    notesLabel: "El nombre de cada persona y su significado, si lo sabes, y cualquier otra cosa que deba saber la profesora (opcional)",
    notesHint: "p. ej. Emma — «entera, universal»; Liam — «protector decidido». Una persona es zurda…",
    flow: [
      { title: "Elige una fecha y envía tu solicitud", body: "Elige una de las fechas publicadas y una hora de inicio. Añade el nombre de cada persona y su significado si lo sabes." },
      { title: "Respondemos en 24 horas", body: "Con la disponibilidad de la clase ese día, el precio y las condiciones." },
      { title: "Paga para confirmar", body: "La reserva se confirma cuando llega tu pago; las condiciones de cancelación empiezan entonces. Después te pedimos lo que necesita la profesora: el nombre y significado de cada persona, la nacionalidad y un teléfono para ese día." },
    ],
    faq: [
      { q: "¿Necesito experiencia?", a: "No. La clase empieza por los trazos básicos y la profesora adapta el ritmo a tu grupo." },
      { q: "Mi letra no es bonita. ¿Importa?", a: "En absoluto. La clase no consiste en escribir a la perfección, sino en lo que el kanji significa para ti y en expresarlo a tu manera. Eliges un estilo —Cute, Bold o Elegant— y la profesora te guía paso a paso." },
      { q: "¿Cómo se eligen kanji para un nombre que no es japonés?", a: "Por su significado. Antes de la clase te preguntamos qué significa tu nombre y de dónde viene, en la medida en que lo sepas. La profesora prepara tres caracteres que transmiten ese significado o esa imagen, y te explica cada uno el día de la clase. Si prefieres no usar tu nombre, dinos una palabra: luz, sueño, valor." },
      { q: "¿Qué me llevo a casa?", a: "Tu obra final sobre un shikishi, con sello rojo, y un soporte de madera para exponerla." },
      { q: "¿En qué idioma es la clase?", a: "En inglés: la profesora la imparte en inglés sencillo." },
      { q: "¿Pueden venir niños?", a: "Desde 10 años, porque se usa tinta de verdad. Pagan el precio de adulto." },
      { q: "Viajo solo/a. ¿Puedo participar?", a: "Sí. Una clase para una persona se cobra como dos; el cuadro de reserva muestra el total al elegir una persona." },
      { q: "¿Qué ropa llevo?", a: "Ropa que no te importe manchar de tinta. Hay delantales." },
      { q: "¿Se puede reservar con poca antelación?", a: "Sí, hasta las 18:00 (hora de Japón) del día anterior. Algunos días el estudio se reserva solo cuando llega una solicitud, así que para una clase en los próximos días solo podemos confirmar si el estudio sigue libre." },
      { q: "¿Cómo funciona la reserva?", a: "Elige una fecha publicada y envía la solicitud; respondemos en 24 horas con el precio y las condiciones. Enviar la solicitud no cuesta nada. La reserva se confirma cuando pagas con el enlace que te enviamos y las condiciones de cancelación empiezan entonces." },
      { q: "¿Y si llegamos tarde?", a: "El estudio se alquila por horas: la clase termina a su hora y la práctica se acorta. Avísanos en cuanto sepas que llegas tarde." },
      { q: "¿Está incluido el transporte?", a: "No. Te encuentras con la profesora en el estudio de Shinjuku; la dirección y las indicaciones llegan con la confirmación." },
    ],
    whatYoullDo: ["Aprender los trazos básicos del pincel", "Elegir kanji con el significado de tu nombre", "Pintar tu obra final sobre un shikishi", "Llevártela sellada y en su soporte"],
    master: { title: "Tu profesora", bio: "Tu profesora enseña fude-moji, caligrafía expresiva con pincel, en Tokio y da ella misma cada clase.", quote: "" },
    itinerary: ["10:30 — Bienvenida", "10:50 — Práctica con el pincel y elección de tu kanji", "11:10 — Tu estilo: Cute, Bold o Elegant", "11:40 — Tu obra final", "12:00 — Sello, compartir y fotos", "12:15 — Tiempo libre"],
    goodToKnow: ["Desde 10 años; los niños pagan el precio de adulto.", "Ropa que no te importe manchar; hay delantales.", "Clase en inglés sencillo."],
    story: { heading: "Por qué un nombre en kanji", body: "Los kanji tienen significado, no solo sonido. Elegir caracteres para un nombre es como muchos padres japoneses nombran a sus hijos, y convierte un recuerdo en algo que habla de ti." },
  },
  {
    slug: "mt-fuji-golf-day", city: "tokyo", category: "golf",
    title: "Experiencia privada de golf en el monte Fuji, desde Tokio",
    tagline: "Disfruta de una vuelta memorable en la región del monte Fuji, con tu hora de salida y los detalles del día organizados personalmente para ti. Un coche privado desde tu hotel de Tokio, apoyo en inglés y comida en la casa club completan un día pensado solo para vosotros.",
    overview: [
      "Haz del golf uno de los momentos estrella de tu viaje a Japón. Deja Tokio atrás por un día de golf privado en la región del monte Fuji, con tu propio coche y los preparativos resueltos. Disfruta de la vuelta, siéntate a comer en la casa club y vuelve a tu hotel con un día que merece la pena recordar.",
      "Nos ocupamos de la reserva de la hora de salida, de los traslados y de los palos de alquiler, con apoyo en inglés para orientarte durante el día. Tú eliges la hora de salida desde tu hotel, entre las 5:00 y las 7:00; nosotros proponemos el campo y la hora de salida a juego, y los ves, con el precio final, antes de pagar. Menos tiempo organizando. Más tiempo disfrutando del golf.",
    ],
    duration: "Día completo, de hotel a hotel", price: "¥180,000", group: "Coche privado y guía · 2–4 golfistas", ages: "Desde 18 años", area: "Región del monte Fuji (recogida en Tokio)",
    img: "/images/golf-flag-fuji.jpg", alt: "Un green con su bandera, el monte Fuji alzándose tras los pinos",
    gallery: [
      { img: "/images/golf-fuji-clouds.jpg", alt: "El monte Fuji sobre las nubes, visto desde el campo" },
      { img: "/images/golf-fairway.jpg", alt: "Una calle y un búnker bajo el monte Fuji a principios de verano" },
      { img: "/images/golf-pond.jpg", alt: "El monte Fuji reflejado en un estanque junto a la calle" },
      { img: "/images/golf-green.jpg", alt: "Golfistas en el green, con el monte Fuji al fondo" },
      { img: "/images/golf-swing.jpg", alt: "Un golpe de salida hacia el monte Fuji" },
    ],
    galleryNote: "Las fotos muestran campos de la región del monte Fuji. Tu campo se propone para tu fecha, y el monte Fuji solo se ve en días despejados.",
    langTag: "Guía de golf que habla inglés",
    timeLabel: "Salida desde tu hotel",
    scheduleNote: "Horarios para una salida a las 6:00. Elige cualquier salida entre las 5:00 y las 7:00 al consultar; proponemos una hora de salida al tee a juego, y el resto del día se desplaza con ella.",
    cta: {
      label: "Planear mi día de golf privado",
      note: "Consultar no cuesta nada. Revisa tu campo, tu hora de salida y el precio final antes de reservar.",
      heading: "Tu día de golf en el monte Fuji empieza aquí",
      lead: "Consultar no cuesta nada. Revisa tu campo, tu hora de salida y el precio final antes de reservar. Para la mayor variedad de campos y horas de salida, te recomendamos consultar con al menos 30 días de antelación.",
    },
    includedShort: "Coche privado desde tu hotel · Vuelta con apoyo en inglés · Palos y comida",
    cancellation: "Los días se cuentan hasta la fecha de tu vuelta, en hora de Japón; la cancelación gratuita termina a las 18:00 siete días antes. La fecha puede cambiarse hasta 14 días antes si hay otra hora de salida libre, y el número de golfistas puede reducirse hasta 7 días antes. Si el campo cierra por el tiempo, lo decide el mismo día y se te reembolsa todo salvo los gastos ya incurridos, como el coche si ya ha salido.",
    highlights: [
      { icon: "car", title: "Tu hotel. Tu coche privado. Tu día de golf.", body: "Viaja de tu hotel de Tokio al campo y de vuelta con comodidad, saliendo a la hora que elijas entre las 5:00 y las 7:00, sin transporte que organizar ni rutas desconocidas." },
      { icon: "flag", title: "Una vuelta memorable en la región del monte Fuji", body: "Organizamos tu campo y tu hora de salida, y te contamos los detalles antes de que decidas reservar." },
      { icon: "interpreter", title: "Apoyo local para un día sin complicaciones", body: "Ayuda con el check-in, la etiqueta de la casa club y los detalles prácticos, para que estés tranquilo y te concentres en tu vuelta. Con dos o tres golfistas, tu guía juega la vuelta contigo; un grupo de cuatro juega con un caddie del campo." },
      { icon: "photo", title: "Una vuelta para recordar. Un recuerdo para llevarte.", body: "Revive el día con un breve vídeo de los mejores momentos y un marcador de bola personalizado con tu nombre en kanji." },
    ],
    included: [
      "Coche privado de tu hotel de Tokio al campo y de vuelta, con salida a la hora que elijas (de 5:00 a 7:00)",
      "Green fee de una vuelta en un campo de la región del monte Fuji, propuesto para tu fecha",
      "Palos de alquiler",
      "Un guía de golf que habla inglés, viaja contigo, se encarga del check-in y juega la vuelta con grupos de dos o tres; con cuatro golfistas, en su lugar acompaña al grupo un caddie del campo (inglés no garantizado)",
      "Comida en la casa club",
      "Un vídeo con los mejores momentos de tu día, de un minuto aproximadamente, que se envía después",
      "Un marcador de bola de golf con tu nombre en kanji",
      "Impuestos, incluidos en el precio indicado",
    ],
    notIncluded: [
      "Zapatos de golf: trae los tuyos, o pídenoslo y consultaremos el alquiler con el campo",
      "Fotografía y vídeo profesionales (extra opcional, más abajo)",
      "Los grupos de cinco o seis se presupuestan bajo petición",
    ],
    addOns: [
      { id: "pro-video", name: "Fotografía y vídeo profesionales", description: "Tu guía filma el día con una cámara dedicada y te entrega un montaje de uno a dos minutos. ¥120,000 para dos golfistas, ¥144,000 para tres; para cuatro, a consultar.", price: 120000, priceFrom: true },
    ],
    schedule: [
      { time: "05:55", title: "Encuentro en el vestíbulo de tu hotel", body: "Tu guía y el conductor se reúnen contigo cinco minutos antes de la hora de salida que elegiste." },
      { time: "06:00", title: "Salida de Tokio", body: "Unas dos horas en coche privado hasta la región del monte Fuji." },
      { time: "08:00", title: "Llegada y check-in", body: "Tu guía hace el check-in, se ocupa de los palos de alquiler y te explica el campo y las costumbres de la casa club." },
      { time: "08:30", title: "Salida desde el tee", body: "Tu vuelta, con tu guía (o, con cuatro golfistas, un caddie del campo) a tu lado, ayudándote con el campo sobre la marcha." },
      { time: "Después de la vuelta", title: "Comida en la casa club", body: "La comida está incluida." },
      { time: "Por la tarde", title: "Regreso a tu hotel", body: "El coche te lleva de vuelta a Tokio; tu vídeo con los mejores momentos llega después por correo electrónico." },
    ],
    venue: {
      heading: "Tu campo, organizado personalmente",
      lead: "Dinos tu fecha preferida y tus preferencias de campo, si las tienes. Comprobamos la disponibilidad y te enviamos el campo propuesto, la hora de salida y el precio final antes de que hagas ningún pago.",
      knownHeading: "Antes de pagar", afterHeading: "Una vez confirmada la reserva",
      known: ["El campo propuesto (en la región del monte Fuji, la zona de Fuji–Hakone, a unos 90 a 150 km del centro de Tokio) y su hora de salida, enviados con tu presupuesto", "El precio final para tu grupo", "Recogida y regreso en tu hotel de Tokio, con salida entre las 5:00 y las 7:00 a tu elección"],
      afterBooking: ["El nombre de tu guía y su contacto para ese día", "Los datos del coche y del conductor", "Dónde encontraros en el vestíbulo de tu hotel"],
      img: "/images/golf-pond.jpg", alt: "El monte Fuji reflejado en un estanque junto a la calle",
    },
    notesLabel: "Tu hotel en Tokio, el nivel o hándicap de cada golfista, tus preferencias de campo y cualquier otra cosa que debamos saber (opcional)",
    notesHint: "p. ej. Hotel en Shinjuku; hándicaps 12 y 20; uno de nosotros necesita palos para zurdos",
    flow: [
      { title: "Dinos tu fecha y tus preferencias", body: "Elige una fecha y una hora de salida, e indica tu hotel, el número de golfistas, vuestro nivel aproximado y el campo que tengas en mente, si lo hay. Enviar la solicitud no cuesta nada." },
      { title: "Una primera respuesta en 24 horas", body: "Confirmamos tu solicitud y buscamos campos para tu fecha. El campo propuesto, la hora de salida y el precio final suelen llegar en un día laborable; para las solicitudes enviadas en fin de semana, la hora de salida puede confirmarse el lunes." },
      { title: "Revisa y paga para confirmar", body: "Repasa el campo, la hora de salida y el precio. La reserva se confirma cuando llega tu pago, y las condiciones de cancelación empiezan entonces. Después te enviamos el contacto de tu guía y los datos del coche." },
    ],
    faq: [
      { q: "¿En qué campo jugaremos?", a: "En un campo de la región del monte Fuji (la zona de Fuji–Hakone, a unos 90 a 150 km del centro de Tokio), propuesto para tu fecha. Verás el nombre del campo y la hora de salida con tu presupuesto, antes de pagar. Si tienes un campo en mente, indícalo en tu solicitud y lo intentaremos." },
      { q: "¿El coche y el guía son solo para nosotros?", a: "Sí. Tu grupo viaja en su propio coche con tu guía. Con dos o tres golfistas, el guía juega la vuelta con el grupo; con cuatro, en su lugar acompaña al grupo un caddie del campo, que puede no hablar inglés." },
      { q: "¿Cuándo y dónde nos recogen?", a: "En tu hotel de Tokio, a la hora de salida que elijas: 5:00, 5:30, 6:00, 6:30 o 7:00. El trayecto dura unas dos horas. Indica el hotel en tu solicitud; si está fuera del centro de Tokio, consúltanos y lo comprobaremos." },
      { q: "¿Qué hora de salida elegimos?", a: "Una salida más temprana supone una hora de salida al tee más temprana y más tarde libre; salir a las 7:00 supone jugar y volver más tarde. Proponemos una hora de salida al tee acorde con tu hora de salida y te avisamos si el campo solo tiene otras horas." },
      { q: "¿Hay código de vestimenta?", a: "Sí. Los clubes japoneses esperan chaqueta al llegar a la casa club y camisa con cuello en el campo. Tu guía te explica el resto ese día." },
      { q: "¿Están incluidos los palos? ¿Y los zapatos?", a: "Los palos de alquiler están incluidos. Trae tus propios zapatos de golf; si necesitas alquilar un par, dinos tu talla y lo consultaremos con el campo." },
      { q: "¿Quién puede participar?", a: "Golfistas de 18 años o más, de dos a cuatro por reserva. Para cinco o seis, consúltanos y te enviaremos un presupuesto." },
      { q: "¿Y si llueve?", a: "Si el campo cierra por el tiempo, lo decide el propio campo el mismo día; se te reembolsa todo salvo los gastos ya incurridos, como el coche si ya ha salido." },
      { q: "¿Y si llegamos tarde?", a: "El coche espera 15 minutos en tu hotel. Pasado ese tiempo podríamos perder la hora de salida y no poder jugar, y las condiciones de cancelación se aplican como si no te hubieras presentado." },
      { q: "¿Con cuánta antelación hay que reservar?", a: "Si puedes, con al menos 30 días de antelación: cuanto antes consultes, más campos y horas de salida habrá para elegir. Las solicitudes cierran a las 18:00 hora de Japón tres días antes; a menos de siete días de la fecha solo podemos confirmar si todavía puede encontrarse una hora de salida." },
      { q: "¿Cómo funciona la reserva?", a: "Elige una fecha y envía la solicitud; no cuesta nada. Respondemos en 24 horas y te enviamos el campo propuesto, la hora de salida y el precio final antes de que pagues. La reserva se confirma cuando pagas con el enlace que te enviamos, y las condiciones de cancelación empiezan entonces." },
    ],
    whatYoullDo: ["Viajar de tu hotel al campo en coche privado", "Jugar una vuelta en la región del monte Fuji, con los detalles del día organizados para ti", "Comer en la casa club", "Volver a Tokio y recibir después tu vídeo con los mejores momentos"],
    master: { title: "Tu guía de golf", bio: "Un guía que habla inglés, de nuestro socio de golf, que organiza el campo, viaja contigo y juega la vuelta con grupos de dos o tres.", quote: "" },
    itinerary: ["05:55 — Encuentro en el vestíbulo de tu hotel (cinco minutos antes de tu salida)", "06:00 — Salida de Tokio", "08:00 — Llegada y check-in", "08:30 — Salida desde el tee", "Después de la vuelta — Comida en la casa club", "Por la tarde — Regreso a tu hotel"],
    goodToKnow: ["Desde 18 años.", "Recogida en tu hotel de Tokio a las 5:00, 5:30, 6:00, 6:30 o 7:00, a tu elección.", "Vestimenta en la casa club: chaqueta al llegar, camisa con cuello en el campo.", "Los palos de alquiler están incluidos; trae zapatos de golf."],
    story: { heading: "El golf a la japonesa", body: "En Japón, el golf tiene sus propios rituales: la chaqueta al llegar, el cuidado del campo, la comida sin prisas. Jugado a la vista del monte Fuji en una mañana despejada, es otro juego." },
  },
  {
    slug: "sushi-masterclass", city: "tokyo", category: "sushi",
    title: "Clase magistral de sushi Edo-mae",
    tagline: "Moldea nigiri con un chef de tercera generación en su propia barra",
    duration: "2,5 horas", price: "¥45.000", group: "Privado · máx. 6", ages: "A partir de 8 años", area: "Tokio (zona de Tsukiji)",
    img: "/images/exp-sushi.jpg", alt: "Barra de sushi omakase de madera de hinoki",
    gallery: [{ img: "/images/cat-sushi.jpg", alt: "Chef de sushi cortando pescado sobre una tabla de madera" }],
    whatYoullDo: [
      "Siéntate en la barra del propio chef, cerrada al público durante tu sesión.",
      "Aprende a moldear el shari, sazonar el neta y prensar nigiri con su corrección directa.",
      "Prueba cada pieza recién hecha, tal y como debe comerse el sushi Edo-mae.",
      "Termina con la selección del chef, servida para ti como su invitado.",
    ],
    master: { quote: "Mi abuelo sostenía mis manos sobre el arroz. Hoy, yo sostengo las tuyas.", title: "Un chef de sushi Edo-mae de tercera generación", bio: "Se formó con su padre y su abuelo en la misma barra donde tú estarás, en un barrio marcado por el antiguo mercado de Tsukiji. Rara vez acepta alumnos; esta sesión es la excepción. El nombre de su local se comparte al confirmar la reserva." },
    itinerary: ["10:00 — Encuentro con tu guía intérprete cerca del local", "10:15 — Presentaciones, delantal, corte y shari", "11:15 — Moldeado de nigiri en la barra", "12:00 — Degustación y plato final del chef", "12:30 — Fin de la experiencia"],
    goodToKnow: ["Se celebra por la mañana, antes de abrir el local; los días exactos dependen de la agenda del chef.", "El pescado crudo es el centro de la sesión — cuéntanos tus alergias y lo adaptamos.", "Es práctica y de pie la mayor parte del tiempo; se facilitan delantales.", "Puedes hacer fotos; pedimos que la fachada y los rótulos queden fuera del encuadre."],
    story: { heading: "La historia del sushi Edo-mae", body: "Edo-mae — «frente a Edo» — designaba el pescado de la bahía de Tokio, curado, prensado o marcado para aguantar un día sin hielo. Las técnicas sobrevivieron a la refrigeración porque saben mejor, no por ser antiguas. Lo que aprenderás en esta barra es ese repertorio: vinagre, sal, kombu y tiempo, pieza a pieza." },
  },
  {
    slug: "sumo-morning-practice", city: "tokyo", category: "sumo",
    title: "Dentro del entrenamiento matinal de sumo",
    tagline: "A pie de ring en una cuadra en activo mientras arranca el día",
    duration: "2 horas", price: "¥38.000", group: "Grupo reducido · máx. 8", ages: "A partir de 10 años", area: "Tokio (zona de Ryogoku)",
    img: "/images/exp-sumo.jpg", alt: "Luchadores de sumo entrenando en el ring de una cuadra de Tokio",
    gallery: [{ img: "/images/cat-sumo.jpg", alt: "Luchadores de sumo en la ceremonia de entrada al ring" }],
    whatYoullDo: [
      "Entra con tu guía en una cuadra de sumo en activo antes de que despierte la ciudad.",
      "Observa el keiko — el entrenamiento matinal — desde tatamis a pocos metros del ring.",
      "Entiende cada ejercicio y ritual sobre la marcha, en tu idioma.",
      "Saluda brevemente a los luchadores tras la práctica, si su agenda lo permite.",
    ],
    master: { quote: "El entrenamiento no es un espectáculo. Pero esta mañana, la puerta está abierta para ti.", title: "Una cuadra de sumo del barrio de Ryogoku", bio: "La cuadra lleva décadas formando luchadores clasificados en el barrio histórico del sumo de Tokio. Las visitas son limitadas para no perturbar la práctica; tu guía te explicará la etiqueta antes de entrar. El nombre de la cuadra se comparte al confirmar la reserva." },
    itinerary: ["07:30 — Encuentro con tu guía intérprete en Ryogoku", "07:45 — Normas de etiqueta y entrada a la cuadra", "08:00 — Entrenamiento matinal desde los tatamis", "09:15 — Breve saludo con los luchadores (según agenda)", "09:30 — Fin de la experiencia"],
    goodToKnow: ["La práctica sigue el calendario de torneos; algunas semanas no hay disponibilidad.", "Se exige silencio durante el entrenamiento; tu guía traduce en susurros.", "Estarás sentado en tatami hasta 90 minutos; hay cojines disponibles.", "Viste con discreción; no se permite flash dentro de la cuadra."],
    story: { heading: "El mundo dentro de una cuadra de sumo", body: "El sumo profesional se vive, no solo se representa. Los luchadores comparten techo, cocina y una jerarquía estricta, y el ring matinal es donde todo se hace visible: los novatos barren el dohyo, los veteranos pelean los últimos y más duros combates. Ver el keiko es ver toda la sociedad de este deporte de una vez." },
  },
  {
    slug: "kimono-photo-walk", city: "tokyo", category: "kimono",
    title: "Vestido de kimono y paseo por el jardín",
    tagline: "Vestido por una estilista profesional y paseo por un jardín clásico",
    duration: "3 horas", price: "¥40.000", group: "Privado · máx. 4", ages: "Todas las edades", area: "Tokio (barrio de jardines tradicionales)",
    img: "/images/exp-kimono.jpg", alt: "Mujer en kimono rojo junto a un estanque de carpas en un jardín japonés",
    gallery: [{ img: "/images/cat-kimono.jpg", alt: "Kimono antiguo de seda con motivo de faisanes y peonías" }],
    whatYoullDo: [
      "Elige entre un vestuario seleccionado de kimonos de seda acordes a la estación.",
      "Déjate vestir como es debido — cada capa, pliegue y nudo — por una estilista profesional.",
      "Pasea por un jardín clásico mientras tu guía te cuenta su diseño y su historia.",
      "Disfruta de tiempo sin prisas para fotos en los mejores rincones del jardín.",
    ],
    master: { quote: "Un kimono no se pone: se construye. Y yo lo construiré sobre ti.", title: "Una estilista profesional de kimono", bio: "Lleva más de veinte años vistiendo a clientes para bodas, ceremonias y rodajes, y elige cada conjunto según la persona y la estación, no de un perchero de disfraces. La ubicación de su estudio se comparte al confirmar la reserva." },
    itinerary: ["10:00 — Encuentro con tu guía intérprete en el estudio", "10:15 — Selección del kimono y vestido", "11:15 — Paseo por el jardín y fotografías", "12:45 — Regreso, cambio de ropa y té", "13:00 — Fin de la experiencia"],
    goodToKnow: ["Hay kimonos en una amplia gama de tallas; dinos tu altura con antelación.", "Caminar cómodo es parte de la experiencia; se facilitan calcetines tabi.", "Si llueve, el paseo sigue por los caminos cubiertos y la casa de té del jardín.", "Se puede añadir un fotógrafo profesional bajo petición."],
    story: { heading: "Por qué importa el vestido", body: "Un kimono no se pone; se construye — capa sobre capa, ajustado al cuerpo hasta que la silueta es la correcta. Bien vestido cambia tu forma de estar y de caminar, y por eso el jardín viene después del vestidor: fue diseñado para quien pasea al ritmo de un kimono." },
  },
  {
    slug: "katana-forge-visit", city: "tokyo", category: "swordsmith",
    title: "Katana: visita la fragua de un forjador",
    tagline: "Observa a un forjador titulado plegar el acero al modo tradicional",
    duration: "3 horas", price: "¥90.000", group: "Privado · máx. 4", ages: "A partir de 12 años", area: "Gran Tokio (zona de talleres)",
    img: "/images/cat-sword.jpg", alt: "Hoja de katana pulida fotografiada sobre negro",
    gallery: [],
    whatYoullDo: [
      "Viaja con tu guía hasta una fragua en activo que rara vez abre sus puertas.",
      "Observa el acero tamahagane calentarse, martillearse y plegarse en el yunque.",
      "Sostén hojas terminadas y descubre cómo el pulidor revela el hamon.",
      "Pregunta lo que quieras al forjador — tu guía traduce toda la conversación.",
    ],
    master: { quote: "El acero recuerda cada golpe. Ven a verlo recordar.", title: "Un forjador de espadas japonés titulado", bio: "Es uno de los pocos herreros autorizados hoy para forjar nihonto, y trabaja en la fragua tradicional de carbón con un único aprendiz. Los días de forja son irregulares, así que las fechas se confirman una a una. La ubicación de la fragua se comparte al confirmar la reserva." },
    itinerary: ["09:30 — Encuentro con tu guía intérprete; viaje juntos a la fragua", "10:30 — Introducción a la fragua y sus herramientas", "11:00 — Demostración de forja en el yunque", "12:00 — Manejo de hojas y preguntas con el forjador", "12:30 — Fin de la experiencia (regreso con tu guía)"],
    goodToKnow: ["La fragua es calurosa y ruidosa durante las demostraciones; se facilita protección auditiva.", "Cerca del fuego se requiere calzado cerrado y ropa de fibras naturales.", "Las fechas dependen del calendario de producción del forjador — reserva pronto.", "Las hojas se manejan solo bajo la supervisión directa del maestro."],
    story: { heading: "Mil años en una sola curva", body: "La espada japonesa sobrevive porque su elaboración nunca se simplificó. El acero se sigue fundiendo a partir de arena de hierro, se pliega para expulsar impurezas y se templa en agua creando la curva y el hamon en un único instante de riesgo. Cada forjador titulado en activo es una línea directa con ese método intacto." },
  },
  {
    slug: "anime-nail-art-session", city: "tokyo", category: "anime-nail-art",
    title: "Sesión de nail art de anime",
    tagline: "Tu personaje favorito, pintado por una artista de uñas de Tokio",
    duration: "2 horas", price: "¥18.000", group: "Privado · máx. 2", ages: "Todas las edades", area: "Tokio (zona de Akihabara / Harajuku)",
    img: "/images/cat-nail.jpg", alt: "Calle de Akihabara iluminada de neón por la noche",
    gallery: [],
    whatYoullDo: [
      "Comparte con antelación tus personajes o ilustraciones favoritas con la artista.",
      "Observa cómo nacen ilustraciones diminutas pintadas a mano, uña a uña.",
      "Charla con la artista sobre la cultura del nail art y el fan art de Tokio mientras trabaja.",
      "Llévate un arte en gel duradero — y sus consejos de cuidado.",
    ],
    master: { quote: "Tráeme a tu personaje favorito. Lo pintaré en ocho milímetros.", title: "Una artista de uñas especializada en personajes de Tokio", bio: "Su agenda la llenan fans que vuelan hasta aquí por su trabajo pintado a mano, desde franquicias clásicas hasta los estrenos de esta temporada. Pinta a pulso con pinceles más finos que la mina de un lápiz. La ubicación de su salón se comparte al confirmar la reserva." },
    itinerary: ["14:00 — Encuentro con tu guía intérprete en el salón", "14:10 — Consulta de diseño sobre tus referencias", "14:30 — Sesión de pintura", "15:50 — Capa final y cuidados", "16:00 — Fin de la experiencia"],
    goodToKnow: ["Envía imágenes de referencia al reservar para que la artista prepare los colores.", "El arte en gel suele durar de tres a cuatro semanas con uso normal.", "Los diseños complejos pueden alargar la sesión; el horario se confirma antes.", "Esta experiencia tiene un precio más ligero que nuestras clases magistrales — no por ello menos artesanal."],
    story: { heading: "Fan art que puedes llevar puesto", body: "El nail art creció junto a la cultura de personajes de Japón, y en Tokio ambos se fundieron en un género propio: microilustración pintada sobre un lienzo móvil más pequeño que un sello. Las mejores artistas tienen lista de espera de semanas entre el público local. Esta sesión te abre una de esas sillas." },
  },
  {
    slug: "evening-with-geiko", city: "kyoto", category: "geisha", bookingType: "request", status: "live",
    title: "Banquete ozashiki con maiko y geiko",
    tagline: "Dos horas privadas en Kioto con una geiko o maiko. Compartid una cena japonesa de temporada, conversad en la mesa, ved una danza tradicional y jugad a los juegos ozashiki — con un guía intérprete durante toda la velada, en español, inglés o francés.",
    duration: "2 horas", price: "¥161.000", priceUnit: "group", group: "Privado · 2–40 personas", ages: "Todas las edades", area: "Kioto (zona de Gion / Higashiyama)",
    img: "/images/geiko-photo-together.jpg", alt: "Dos huéspedes y una maiko sonríen para una foto de recuerdo en una sala privada de Kioto",
    gallery: [
      { img: "/images/geiko-conversation.jpg", alt: "Conversación durante la cena, con el intérprete en ambos sentidos", caption: "Conversación durante la cena, con el intérprete en ambos sentidos" },
      { img: "/images/geiko-maiko-seated.jpg", alt: "Una maiko se sienta junto a su mesa", caption: "Una maiko se sienta junto a su mesa" },
      { img: "/images/geiko-dance.jpg", alt: "Una danza ante el biombo dorado", caption: "Una danza ante el biombo dorado" },
      { img: "/images/geiko-dinner-set.jpg", alt: "La cena japonesa de varios platos (el menú cambia con la temporada)", caption: "La cena japonesa de varios platos (el menú cambia con la temporada)" },
      { img: "/images/geiko-maiko-smile.jpg", alt: "Una maiko en la sala privada", caption: "Una maiko en la sala privada" },
      { img: "/images/geiko-pouring.jpg", alt: "Su anfitriona sirve la bebida; pregúntele lo que quiera", caption: "Su anfitriona sirve la bebida; pregúntele lo que quiera" },
      { img: "/images/geiko-games-table.jpg", alt: "Juegos de ozashiki en la mesa", caption: "Juegos de ozashiki en la mesa" },
      { img: "/images/geiko-game-toratora.jpg", alt: "Tora-tora, un piedra-papel-tijera que se juega con todo el cuerpo", caption: "Tora-tora, un piedra-papel-tijera que se juega con todo el cuerpo" },
      { img: "/images/geiko-room-upstairs.jpg", alt: "Una sala del piso superior al estilo de las casas de té de Gion", caption: "Una sala del piso superior al estilo de las casas de té de Gion" },
      { img: "/images/geiko-room-garden.jpg", alt: "Una sala de la planta baja con vistas al jardín interior", caption: "Una sala de la planta baja con vistas al jardín interior" },
    ],
    cancellation: "Los días se cuentan hasta la fecha de la experiencia, hora de Japón. Los cambios de fecha siguen la misma escala y reducir el grupo aplica la tarifa a las plazas liberadas; los reembolsos se hacen por el mismo método de pago. Si no puede asegurarse ninguna geiko o maiko para tu fecha, recibes el reembolso completo sea cual sea el momento.",
    whatYoullDo: [
      "Acomódate en tu propio salón de banquete privado — nunca compartido con otros clientes.",
      "Cena cocina de temporada de Kioto mientras tu geiko o maiko se une a tu mesa para conversar.",
      "Contempla una danza a un brazo de distancia y prueba los juegos de sobremesa ozashiki.",
      "Termina con fotos conmemorativas junto a tus anfitrionas.",
    ],
    master: { quote: "Por una noche, esta sala es tuya. Ven, hablemos.", title: "Geiko y maiko del hanamachi de Kioto", bio: "Tu velada la acogen geiko o maiko en activo del mundo de la flor y el sauce de Kioto, contratadas especialmente para tu fecha. El local es una casa de banquetes privada del barrio de Gion / Higashiyama; su nombre y dirección se comparten al confirmar la reserva." },
    itinerary: ["10 min antes — Llegada al local con tu guía (dirección en la confirmación)", "0:00 — Bienvenida a tu salón privado; comienza el banquete", "0:30 — Geiko y maiko se unen a tu mesa; conversación durante la cena", "1:00 — Danza y juegos de sobremesa ozashiki", "1:50 — Fotos conmemorativas", "2:00 — Fin de la velada"],
    goodToKnow: [
      "Se celebra todos los días salvo las fiestas de Año Nuevo, con inicios entre las 12:00 y las 20:30 — las solicitudes cierran a las 17:00 (hora de Japón) del día anterior.",
      "El precio depende del tamaño del grupo: 2 personas ¥161.000, 3 personas ¥182.000, 4 personas ¥195.000, 5 personas ¥226.000; seis o más, a consultar. El shamisen en directo añade ¥70.000 y dos artistas con shamisen añaden ¥135.000, sea cual sea el tamaño del grupo.",
      "En temporada alta (15 mar – 31 may y 1 oct – 30 nov): 2 personas ¥179.000, 3 personas ¥209.000, 4 personas ¥231.000, 5 personas ¥271.000.",
      "Niños: 2 años o menos gratis sin comida, de 3 a 11 años mitad de la tarifa de adulto, desde 12 años tarifa de adulto con el menú completo.",
      "Atendemos alergias y restricciones alimentarias — indícalo al reservar.",
      "¿Música en directo o una sala más animada? Elige Con shamisen en directo (una jikata al shamisen en directo) o Dos artistas (dos geiko o maiko más la jikata).",
    ],
    story: { heading: "El mundo del karyukai", body: "El «mundo de la flor y el sauce» de Kioto funciona desde hace tres siglos a base de presentación y confianza. Una geiko no es una artista de alquiler, sino una maestra cuyas veladas se conceden a través de relaciones entre casas de té y mecenas. Sentarte en esa sala, con la conversación fluyendo en tu idioma, es el acceso más raro que ofrece Kioto." },
    availabilityNote: "Cerrado durante las fiestas de Año Nuevo.",
    interactionTime: "unas 1 h 45 min",
    interactionNote: "2 horas en total; la geiko o maiko está en tu mesa unas 1 h 45 min.",
    mapNote: "El marcador indica la estación de Gion-Shijo (línea Keihan); el local está a unos 8 minutos a pie. La dirección exacta llega con la confirmación.",
    includedShort: "Sala privada · Comida y bebida · Guía intérprete (ES / EN / FR)",
    planText: {
      select: { label: "La velada", name: "Private Geisha Evening", performers: "Una geiko o maiko", blurb: "La velada esencial; la danza se acompaña con música grabada." },
      signature: { label: "Con shamisen en directo", name: "Private Geisha Evening with Live Shamisen", performers: "Geiko o maiko + shamisen en directo", blurb: "Una geiko o maiko, acompañada por una jikata que toca el shamisen en directo." },
      reserve: { label: "Dos artistas", name: "The Complete Geisha Evening", performers: "Dos artistas + shamisen en directo", blurb: "Dos geiko o maiko y una jikata con shamisen en directo. La versión más completa de la velada." },
    },
    galleryNote: "La sala y los platos de las fotos son ejemplos; ambos varían según la fecha y la temporada.",
    highlights: [
      { icon: "group", title: "La sala es suya", body: "Un salón de banquete privado solo para su grupo: nunca se comparte con otros huéspedes." },
      { icon: "chat", title: "Conversación, no solo espectáculo", body: "Su geiko o maiko se sienta a su mesa para conversar, baila a un brazo de distancia y luego juega con ustedes a los juegos de ozashiki." },
      { icon: "interpreter", title: "Pregunte lo que quiera", body: "Un guía intérprete lleva la conversación en ambos sentidos: sus preguntas llegan a la sala y las respuestas vuelven a usted." },
    ],
    included: [
      "Una sala privada de tatami para su grupo: las del piso superior imitan una casa de té de Gion, las de la planta baja dan al jardín interior",
      "Una cena japonesa de varios platos: obanzai de temporada, sashimi, un plato de carne, tempura, arroz y sopa, postre (cambia según el mercado)",
      "Bebida libre durante toda la velada: cerveza, sake, shochu, vino, highballs, umeshu y refrescos",
      "Tu geiko o maiko como anfitriona: conversación, una o dos danzas y los juegos de salón Konpira Funefune y Tora-tora (artistas según el plan)",
      "Fotos y vídeo bienvenidos, danza incluida — sin flash ni trípode; su guía explica las normas de la casa —, más fotos de recuerdo con su anfitriona",
      "Cuatro menús a elegir: el kaiseki estándar, vegetariano (con opción sin caldo de pescado), sin gluten o un set de filete de wagyu solo con carne; indícalo al solicitar la fecha",
      "Un guía intérprete — en español, inglés o francés, a tu elección — desde la llegada hasta la despedida: te recibe, explica Kioto y la cultura de los barrios de geishas, la danza y cada plato, y lleva la conversación con tu anfitriona en ambos sentidos",
      "Impuestos y servicio: no se añade nada el día del evento",
    ],
    notIncluded: [
      "Intérpretes en idiomas distintos del español, inglés o francés: consúltanos al solicitar la fecha",
      "Los grupos de seis o más se presupuestan individualmente: hasta 40 personas, grupos mayores a consultar",
    ],
    schedule: [
      { time: "17:50", title: "Llegada con su guía", body: "La dirección figura en su confirmación. Su guía les espera cerca y les acompaña adentro." },
      { time: "18:00", title: "Su sala privada", body: "Toman asiento sobre tatami; llegan los primeros platos y las bebidas.", img: "/images/geiko-room-upstairs.jpg" },
      { time: "18:15", title: "Llega su geiko o maiko", body: "Se une a la mesa directamente desde la okiya y se queda una hora y 45 minutos. Conversación durante la cena, con el intérprete en ambos sentidos.", img: "/images/geiko-conversation.jpg" },
      { time: "19:00", title: "La danza", body: "Una o dos danzas ante el biombo dorado, de 19:00 a 19:30 aproximadamente: con música grabada en La velada, con shamisen en directo en los dos planes con jikata. Las cámaras son bienvenidas.", img: "/images/geiko-dance.jpg" },
      { time: "19:30", title: "Juegos de ozashiki", body: "Konpira Funefune, un juego de ritmo, y Tora-tora, piedra-papel-tijera con todo el cuerpo.", img: "/images/geiko-game-toratora.jpg" },
      { time: "19:50", title: "Fotografías", body: "Fotos de recuerdo con su anfitriona.", img: "/images/geiko-photo-together.jpg" },
      { time: "20:00", title: "Fin de la velada" },
    ],
    venue: {
      known: ["Gion / Higashiyama, Kioto: a unos 8 minutos a pie de la estación Gion-Shijo (línea Keihan)", "Una sala privada en una casa de comidas tradicional: salas tipo casa de té arriba, salas con vistas al jardín abajo", "Se sienta sobre tatami", "Encuentro en el lugar: no se organizan traslados"],
      afterBooking: ["El nombre y la dirección de la casa", "Un mapa e indicaciones a pie desde la estación", "El contacto de su guía para esa noche"],
      img: "/images/geiko-room-garden.jpg", alt: "Una sala de tatami de la planta baja con vistas al jardín interior",
    },
    faq: [
      { q: "¿Será una geiko o una maiko?", a: "Se organiza una geiko o maiko para su fecha. La casa no puede aceptar peticiones de una persona concreta ni de maiko en lugar de geiko; si tiene preferencia la transmitiremos, sin prometerla." },
      { q: "¿Cuánto tarda en confirmarse la fecha?", a: "Respondemos en 24 horas con la disponibilidad de la sala, el precio y las condiciones; esa respuesta todavía no es una reserva. La reserva queda confirmada cuando aceptas esas condiciones pagando a través del enlace que te enviamos; las condiciones de cancelación se aplican desde ese momento. Después la casa asegura a tu geiko o maiko: la solicitud formal se hace como muy tarde 14 días antes de tu fecha (de inmediato para fechas más cercanas). Si no puede asegurarse ninguna, recibes el reembolso completo." },
      { q: "¿Podemos añadir shamisen en directo o una segunda anfitriona?", a: "Sí, para eso están los planes. Con shamisen en directo añade una jikata que toca el shamisen en directo (+¥70.000); Dos artistas incluye dos geiko o maiko más la jikata (+¥135.000). El suplemento es el mismo para cualquier tamaño de grupo. Elija el plan al solicitar la fecha." },
      { q: "¿Podemos hacer fotos durante la danza?", a: "Sí. Fotos y vídeo son bienvenidos en cualquier momento, danza incluida — sin flash ni trípode, siguiendo las normas de la casa que explica su guía —, y al final se reserva tiempo para fotos de recuerdo con su anfitriona." },
      { q: "¿Están incluidas las bebidas? ¿Hay código de vestimenta?", a: "La bebida es libre (cerveza, sake, shochu, vino, highballs, refrescos) y está incluida, igual que impuestos y servicio. No hay código de vestimenta." },
      { q: "¿Nuestra anfitriona comerá y beberá con nosotros?", a: "Normalmente no. Muchas maiko son menores de veinte años y, por costumbre, geiko y maiko no comen en la mesa: sirven, conversan, bailan y juegan. No insista en ofrecerles comida o bebida; es la única norma de etiqueta que su guía mencionará." },
      { q: "¿Atienden necesidades dietéticas y alergias?", a: "Sí. Elige entre el kaiseki estándar, un menú vegetariano (puede prepararse sin caldo de pescado), un menú sin gluten o un set de filete de wagyu para quien no come pescado (ensalada, filete y arroz, servidos de una vez, por lo que su ritmo difiere del de los demás menús). Para alergias o restricciones religiosas, indica los ingredientes que no puedes comer y la cocina los sustituye dentro del menú; no hay menú halal ni kosher certificado y no puede descartarse por completo la contaminación cruzada. Las sustituciones son por alergia o religión, no por preferencia. Indícalo en tu solicitud y la respuesta de la cocina llega con las condiciones, antes de pagar." },
      { q: "¿Pueden venir niños? ¿Cuánto pagan?", a: "Sí. Los niños de 2 años o menos participan gratis sin comida; de 3 a 11 años pagan la mitad de la tarifa de adulto; a partir de 12 años, la tarifa de adulto. A partir de 3 años reciben el mismo menú que los adultos: no hay menú infantil. Cuenta a todos en el número de personas e indica las edades de los niños en tu solicitud; el presupuesto que enviamos aplica la reducción." },
      { q: "¿Con cuánta antelación hay que reservar?", a: "Como muy tarde a las 17:00 hora de Japón del día anterior. Para una fecha en los próximos días respondemos lo antes posible, y solo podemos confirmar si hay una geiko o maiko libre con tan poca antelación; una reserva hecha con menos de 4 días de antelación no es reembolsable una vez pagada, salvo que no pueda asegurarse ninguna. Entre 10 y 14 días de antelación es lo cómodo, y primavera y otoño (marzo–abril, octubre–noviembre) se llenan primero. Durante el Miyako Odori (abril) la casa puede confirmar solo cerca de la fecha. La franja horaria definitiva se confirma con la respuesta de disponibilidad." },
    ],
  },
  {
    slug: "tea-ceremony-with-master", city: "kyoto", category: "tea-ceremony",
    title: "Ceremonia del té con una maestra",
    tagline: "Una hora serena de temae en una sala de té de Kioto, cuenco a cuenco",
    duration: "1,5 horas", price: "¥30.000", group: "Privado · máx. 6", ages: "Todas las edades", area: "Kioto (barrio de templos)",
    img: "/images/craft-hands.jpg", alt: "Anfitriona de la ceremonia del té dejando un cuenco sobre el tatami",
    gallery: [{ img: "/images/cat-tea.jpg", alt: "Anfitriona preparando matcha en una reunión de té al aire libre" }],
    whatYoullDo: [
      "Entra a una sala de té en activo por el sendero de su jardín, como los invitados desde hace siglos.",
      "Contempla un temae completo — la coreografía del carbón, el agua, el batidor y el cuenco.",
      "Bate tu propio cuenco de matcha con la guía de la maestra.",
      "Descubre cómo se eligen utensilios, caligrafía y flores para este día y esta estación.",
    ],
    master: { quote: "Una vez, un encuentro. Este cuenco de té no volverá a existir.", title: "Una maestra de té de Kioto en activo", bio: "Titulada en una de las grandes escuelas del té, practica desde hace más de tres décadas y celebra reuniones durante todo el año. Su sala de té está cerca de uno de los barrios de templos de Kioto; la ubicación exacta se comparte al confirmar la reserva." },
    itinerary: ["10:00 — Encuentro con tu guía intérprete cerca de la sala de té", "10:10 — Sendero del jardín, purificación y entrada", "10:20 — Temae de la maestra, primeros cuencos y dulces", "10:50 — Bate tu propio cuenco; utensilios y conversación", "11:30 — Fin de la experiencia"],
    goodToKnow: ["Se sienta en tatami; puedes estirar las piernas y hay taburetes bajos.", "Se agradecen los calcetines blancos; te lo recordaremos la víspera.", "Los dulces no contienen productos animales; otras necesidades, con aviso.", "El movimiento y las fotos se pausan durante el temae — tu guía te indicará."],
    story: { heading: "Una vez, un encuentro", body: "Ichigo ichie — la idea de que esta reunión, con estas personas, ocurre exactamente una vez — es el corazón de la ceremonia del té. Todo en la sala responde al día: la caligrafía, la flor, el esmalte del cuenco frente a la estación. El ritual no es espectáculo sino atención, ofrecida a los invitados cuenco a cuenco." },
  },
  {
    slug: "kimono-higashiyama-walk", city: "kyoto", category: "kimono",
    title: "Kimono y paseo de farolillos por Higashiyama",
    tagline: "Vestida de seda por las calles más legendarias de Kioto a la hora dorada",
    duration: "3 horas", price: "¥40.000", group: "Privado · máx. 4", ages: "Todas las edades", area: "Kioto (zona de Higashiyama)",
    img: "/images/cat-kimono.jpg", alt: "Kimono antiguo de seda con motivo de faisanes y peonías",
    gallery: [{ img: "/images/city-kyoto.jpg", alt: "Calle Yasaka-dori con farolillos y la pagoda de Yasaka al amanecer" }],
    whatYoullDo: [
      "Déjate vestir en seda acorde a la estación por una profesional del kitsuke de Kioto.",
      "Recorre las calles empedradas de Higashiyama mientras se encienden los farolillos.",
      "Escucha la historia de las calles de la pagoda de boca de tu guía mientras caminas.",
      "Haz una pausa para fotos donde la multitud se disipa y la luz es mejor.",
    ],
    master: { quote: "Camina estas calles en seda a la hora de los farolillos y entenderás por qué seguimos vistiendo así.", title: "Una profesional del kitsuke (vestido de kimono) de Kioto", bio: "Formada en el vestido formal para las temporadas de ceremonias de Kioto, elige de un vestuario de seda vintage y contemporánea, no de poliéster de alquiler. Su estudio en Higashiyama está a un paso de la ruta; la dirección se comparte al confirmar la reserva." },
    itinerary: ["15:30 — Encuentro con tu guía intérprete en el estudio", "15:45 — Selección y vestido", "16:45 — Paseo por Higashiyama: calles de piedra, pagoda y farolillos", "18:15 — Regreso y cambio de ropa", "18:30 — Fin de la experiencia"],
    goodToKnow: ["La ruta es empedrada y con suave pendiente; se te ajustan zori resistentes.", "Las plazas de hora dorada son limitadas — reserva pronto en otoño y primavera.", "Si llueve, el paseo continúa con paraguas tradicionales (salen preciosos en fotos).", "Se puede añadir un fotógrafo profesional bajo petición."],
    story: { heading: "Calles hechas para la seda", body: "Los callejones de Higashiyama los moldearon peregrinos, casas de té y talleres durante cinco siglos, y su escala sigue hecha para una persona a pie en kimono. Recorrerlos en seda a la hora de los farolillos no es disfrazarse: es ver las calles como fueron diseñadas para verse." },
  },
  {
    slug: "kyoto-sushi-class", city: "kyoto", category: "sushi",
    title: "Clase de sushi de Kioto y obanzai",
    tagline: "Saba-zushi prensado y cocina casera de Kioto con un chef veterano",
    duration: "2,5 horas", price: "¥35.000", group: "Privado · máx. 6", ages: "A partir de 8 años", area: "Kioto (centro de la ciudad)",
    img: "/images/cat-sushi.jpg", alt: "Chef cortando pescado sobre una tabla de madera",
    gallery: [],
    whatYoullDo: [
      "Descubre por qué Kioto, sin mar, construyó su propia tradición de sushi con pescado curado.",
      "Prensa tu propio saba-zushi — sushi de caballa — en un molde de madera.",
      "Cocina dos o tres obanzai, los platos caseros de Kioto, junto al chef.",
      "Sentaos juntos a comer lo que habéis preparado, con té de temporada.",
    ],
    master: { quote: "Kioto no tenía mar, así que inventamos nuestro propio sushi. Te enseñaré el truco.", title: "Un chef veterano de Kioto", bio: "Lleva más de treinta años cocinando profesionalmente la cocina casera de Kioto y enseña las técnicas de sushi prensado que la ciudad desarrolló lejos del mar. La ubicación de su cocina se comparte al confirmar la reserva." },
    itinerary: ["10:30 — Encuentro con tu guía intérprete en la cocina", "10:45 — Introducción: el sushi de Kioto, curado y no crudo", "11:00 — Prensado del saba-zushi; cocina de obanzai", "12:15 — Almuerzo juntos en la barra", "13:00 — Fin de la experiencia"],
    goodToKnow: ["La caballa curada es la protagonista; hay alternativas para alergias.", "Totalmente práctica; delantales y todo el equipo incluidos.", "Recetas en inglés para llevar a casa.", "Los ingredientes de mercado hacen que los obanzai cambien con la estación."],
    story: { heading: "Sushi, lejos del mar", body: "Antes del ferrocarril, el pescado fresco de mar no llegaba a Kioto — así que la ciudad perfeccionó la conservación. La caballa salada en la costa viajaba por el «saba kaido», la ruta de la caballa, y se prensaba sobre arroz como saba-zushi. El sushi de Kioto es el sabor de esa geografía, y aún se hace en casa hoy." },
  },
];

export const toursEs: Tour[] = [
  {
    slug: "tokyo-private-day-tour", city: "tokyo", bookingType: "request",
    title: "Tour privado de un día por Tokio",
    tagline: "Ocho horas con un guía titulado, a la medida de tus intereses",
    duration: "8 horas", price: "¥60.000", group: "Grupo privado",
    img: "/images/city-tokyo.jpg", alt: "Puerta Kaminarimon del templo Senso-ji de noche",
    description: "Un día completo en Tokio con un guía privado titulado, planificado alrededor de lo que te importa — gastronomía, artesanía, arquitectura, cultura pop — y capaz de integrar cualquiera de nuestras clases magistrales de Tokio en la ruta. Transporte, horarios y reservas quedan resueltos; tú solo sal del hotel.",
  },
  {
    slug: "kyoto-private-day-tour", city: "kyoto", bookingType: "request",
    title: "Tour privado de un día por Kioto",
    tagline: "Templos, té y callejones con un guía que conoce las horas tranquilas",
    duration: "8 horas", price: "¥60.000", group: "Grupo privado",
    img: "/images/tour-journey.jpg", alt: "Torii bermellón en un sendero del santuario Fushimi Inari",
    description: "Un día completo en Kioto con un guía privado titulado que planifica esquivando las multitudes — puertas tempranas, jardines tranquilos, la calle correcta a la hora correcta. Combínalo con nuestra ceremonia del té, el kimono o la velada con geiko para construir un día que se sienta una sola historia y no una lista.",
  },
];
